import { AudioPlayer, createAudioPlayer, setAudioModeAsync } from "expo-audio";
import { Platform } from "react-native";
import * as Haptics from "expo-haptics";

const SOUNDS = {
  cardFlip: require("@/assets/sounds/card-flip.wav"),
  cardDraw: require("@/assets/sounds/card-draw.wav"),
  shuffle:  require("@/assets/sounds/shuffle.wav"),
  win:      require("@/assets/sounds/win.wav"),
  lose:     require("@/assets/sounds/lose.wav"),
  button:   require("@/assets/sounds/button.wav"),
  wild:     require("@/assets/sounds/wild.wav"),
  // Personality SFX (Task #67) — procedurally synthesized unique waveforms,
  // generated by scripts/gen-personality-sfx.mjs.
  mockLaugh:      require("@/assets/sounds/mock-laugh.wav"),
  applauseSfx:    require("@/assets/sounds/applause.wav"),
  crowdGasp:      require("@/assets/sounds/crowd-gasp.wav"),
  dramaticDrum:   require("@/assets/sounds/dramatic-drum.wav"),
  booSfx:         require("@/assets/sounds/boo.wav"),
  cackleSfx:      require("@/assets/sounds/cackle.wav"),
  victoryFanfare: require("@/assets/sounds/victory-fanfare.wav"),
  menuMusic: require("@/assets/sounds/menu-music.mp3"),
  gameMusic: require("@/assets/sounds/game-music.mp3"),
  searchMusic: require("@/assets/sounds/search-music.mp3"),
  // Task #74 — premium feedback assets generated by
  // scripts/gen-feedback-audio.mjs (procedural waveforms).
  clickPremium:    require("@/assets/sounds/click-premium.wav"),
  ochoLocosVoice:  require("@/assets/sounds/ocho-locos-voice.wav"),
  casinoAmbience:  require("@/assets/sounds/casino-ambience.wav"),
  // Task #79 — premium logo stinger (rising shimmer + golden chord stab),
  // generated by scripts/gen-logo-stinger.mjs. Plays once per app session
  // when the main menu first mounts to give the brand a sonic identity.
  logoStinger:          require("@/assets/sounds/logo-stinger.wav"),
  // Task #82 — selectable logo intro variants. Players preview & pick one in
  // Settings; the chosen variant replaces the default boot stinger. Files
  // are generated by scripts/gen-logo-stinger.mjs.
  logoStingerCasino:    require("@/assets/sounds/logo-stinger-casino.wav"),
  logoStingerFanfare:   require("@/assets/sounds/logo-stinger-fanfare.wav"),
  logoStingerCinematic: require("@/assets/sounds/logo-stinger-cinematic.wav"),
  logoStingerArcade:    require("@/assets/sounds/logo-stinger-arcade.wav"),
  logoStingerElegant:   require("@/assets/sounds/logo-stinger-elegant.wav"),
  // Task #83 — unique chest-opening SFX per rarity. Procedurally synthesized
  // by scripts/gen-chest-open-sfx.mjs so each rarity has its own waveform
  // (creak + rarity-specific shimmer/fanfare/tail) instead of remixing
  // existing card/personality samples.
  chestOpenCommon:    require("@/assets/sounds/chest-open-common.wav"),
  chestOpenRare:      require("@/assets/sounds/chest-open-rare.wav"),
  chestOpenMagic:     require("@/assets/sounds/chest-open-magic.wav"),
  chestOpenEpic:      require("@/assets/sounds/chest-open-epic.wav"),
  chestOpenEvent:     require("@/assets/sounds/chest-open-event.wav"),
  chestOpenFichas:    require("@/assets/sounds/chest-open-fichas.wav"),
  chestOpenGiant:     require("@/assets/sounds/chest-open-giant.wav"),
  chestOpenLegendary: require("@/assets/sounds/chest-open-legendary.wav"),
  chestOpenSupreme:   require("@/assets/sounds/chest-open-supreme.wav"),
};

type SoundKey = keyof typeof SOUNDS;

// Task #82 — registry of selectable logo intro stingers.
// Task #85 — added "custom" slot for player-provided clips (uploaded or
// recorded). The custom slot has no bundled asset; its source is a runtime
// file:// URI managed via setCustomStingerUri().
export type LogoStingerId = "casino" | "fanfare" | "cinematic" | "arcade" | "elegant" | "custom";
// Task #86 — premium intros are unlocked through the same economy as the rest
// of the cosmetics: "free" stingers are available from the start, "chest"
// stingers drop from chest rewards, and "battle_pass" stingers are claimed at
// a specific premium battle pass tier. The custom slot is always free (it's a
// player-provided clip, not a reward).
export type LogoStingerUnlock =
  | { type: "free" }
  | { type: "chest"; rarity: "common" | "rare" | "epic" | "legendary" }
  | { type: "battle_pass"; tier: number };
export const LOGO_STINGERS: {
  id: LogoStingerId;
  sfxKey: SoundKey;
  durationMs: number;
  unlock: LogoStingerUnlock;
}[] = [
  { id: "casino",    sfxKey: "logoStingerCasino",    durationMs: 1400, unlock: { type: "free" } },
  { id: "fanfare",   sfxKey: "logoStingerFanfare",   durationMs: 1500, unlock: { type: "free" } },
  { id: "arcade",    sfxKey: "logoStingerArcade",    durationMs: 1200, unlock: { type: "chest", rarity: "rare" } },
  { id: "cinematic", sfxKey: "logoStingerCinematic", durationMs: 1600, unlock: { type: "battle_pass", tier: 47 } },
  { id: "elegant",   sfxKey: "logoStingerElegant",   durationMs: 1600, unlock: { type: "chest", rarity: "epic" } },
];
export const DEFAULT_LOGO_STINGER_ID: LogoStingerId = "casino";

// Task #86 — owned-item id used to track stinger unlocks alongside other
// cosmetics in profile.ownedItems. The "custom" slot is intentionally NOT
// tracked here since it isn't a reward — it's a player-provided clip.
export const STINGER_OWNED_PREFIX = "stinger_";
export function getStingerOwnedId(id: LogoStingerId): string {
  return `${STINGER_OWNED_PREFIX}${id}`;
}
export function isStingerUnlocked(id: LogoStingerId, ownedItems: string[] | undefined): boolean {
  if (id === "custom") return true;
  const entry = LOGO_STINGERS.find((s) => s.id === id);
  if (!entry) return false;
  if (entry.unlock.type === "free") return true;
  return (ownedItems ?? []).includes(getStingerOwnedId(id));
}
// Hard cap enforced when picking/recording a custom intro clip.
export const CUSTOM_LOGO_STINGER_MAX_MS = 2000;
// Task #101 — mirror the server's STINGER_MAX_BYTES (server/auth.ts) so the
// trim modal can warn the player when their source clip is too big to be
// trimmed/uploaded *before* they tap Save.
export const CUSTOM_LOGO_STINGER_SOURCE_MAX_BYTES = 5 * 1024 * 1024;
// Task #104 — upper bound on what /profile/stinger/shrink will accept.
// Sources between SOURCE_MAX_BYTES and this cap can be re-encoded down
// to mono 64k AAC by the server so they fit under the trim limit.
// Task #105 — the upload is now a multipart stream (no base64 inflation),
// so the client cap matches the server's multer fileSize cap (30 MB)
// directly. The picker pre-checks this before kicking off the shrink so
// the player gets an immediate "too big to shrink" message instead of a
// 413 round-trip after waiting for the upload to fail.
export const CUSTOM_LOGO_STINGER_SHRINK_MAX_INPUT_BYTES = 30 * 1024 * 1024;

type MusicTrack = "menu" | "search" | "game";

let bgPlayer: AudioPlayer | null = null;
let sfxPlayers: Map<SoundKey, AudioPlayer> = new Map();
// Per-track persistent players. Once created, a track player is kept alive so
// its playback position is preserved across menu↔game transitions — switching
// resumes from where the user left off instead of restarting from 0.
const trackPlayers: Map<MusicTrack, AudioPlayer> = new Map();
let currentTrack: MusicTrack | null = null;
let isMusicEnabled = true;
let isSfxMuted = false;
let isHapticEnabled = true;
let isVoiceFxEnabled = true;
let isBackgrounded = false;
let musicVolume = 0.35;
let sfxVolume = 0.85;
let ambienceVolume = 0.08;
let isInitialized = false;

// ─── Casino ambience layer ────────────────────────────────────────────────────
// Plays UNDER the menu music at very low volume. Independent of bgPlayer so
// switching tracks (menu↔game) does not affect it. Only active while the
// "menu" track is current and music is enabled.
let ambiencePlayer: AudioPlayer | null = null;
let ambienceActive = false;
// Serializes ambience start/stop fades so rapid track-switches can't overlap
// a fade-in with a fade-out (which would leave the ambience stuck partly
// audible or restart the player mid-fade).
let ambienceTransition: Promise<void> | null = null;

// ─── Concurrency lock ─────────────────────────────────────────────────────────
// Ensures only one music transition happens at a time.
// If multiple requests come in during a transition, only the last one is applied.
let transitionInProgress = false;
let pendingTrack: MusicTrack | null = null;
let pendingSequential = false;
let lastRequestedTrack: MusicTrack | null = null;

async function safe(fn: () => Promise<void>) {
  try { await fn(); } catch {}
}

export async function initAudio() {
  if (isInitialized) return;
  try {
    await setAudioModeAsync({ playsInSilentMode: true });
    isInitialized = true;
  } catch {}
}

function getOrCreateSfx(key: SoundKey): AudioPlayer {
  if (sfxPlayers.has(key)) return sfxPlayers.get(key)!;
  const player = createAudioPlayer(SOUNDS[key]);
  player.volume = sfxVolume;
  sfxPlayers.set(key, player);
  return player;
}

export async function preloadSounds() {
  await initAudio();
  const keys: SoundKey[] = [
    "cardFlip", "cardDraw", "shuffle", "button", "wild", "win", "lose",
    // Task #83 — preload chest-open SFX so the first chest opened in a
    // session doesn't suffer first-play decode latency.
    "chestOpenCommon", "chestOpenRare", "chestOpenMagic", "chestOpenEpic",
    "chestOpenEvent", "chestOpenFichas", "chestOpenGiant",
    "chestOpenLegendary", "chestOpenSupreme",
  ];
  for (const k of keys) {
    try { getOrCreateSfx(k); } catch {}
  }
}

// ─── Core: serialized music transition with crossfade ────────────────────────
const FADE_MS = 380;
const FADE_STEPS = 10;

async function fadeOutCurrent() {
  const player = bgPlayer;
  if (!player) return;
  const startVol = player.volume;
  const stepDur = FADE_MS / FADE_STEPS;
  for (let i = 1; i <= FADE_STEPS; i++) {
    const v = startVol * (1 - i / FADE_STEPS);
    await safe(async () => { player.volume = Math.max(0, v); });
    await new Promise<void>((r) => setTimeout(r, stepDur));
  }
}

async function fadeInCurrent() {
  const player = bgPlayer;
  if (!player) return;
  const targetVol = musicVolume;
  const stepDur = FADE_MS / FADE_STEPS;
  await safe(async () => { player.volume = 0; });
  for (let i = 1; i <= FADE_STEPS; i++) {
    const v = targetVol * (i / FADE_STEPS);
    await safe(async () => { player.volume = Math.min(targetVol, v); });
    await new Promise<void>((r) => setTimeout(r, stepDur));
  }
}

function sourceForTrack(track: MusicTrack) {
  if (track === "menu") return SOUNDS.menuMusic;
  if (track === "search") return SOUNDS.searchMusic;
  return SOUNDS.gameMusic;
}

function getOrCreateTrackPlayer(track: MusicTrack): AudioPlayer | null {
  let p = trackPlayers.get(track) ?? null;
  if (p) return p;
  try {
    p = createAudioPlayer(sourceForTrack(track));
    p.volume = 0;
    p.loop = true;
    trackPlayers.set(track, p);
  } catch { p = null; }
  return p;
}

function getOrCreateAmbience(): AudioPlayer | null {
  if (ambiencePlayer) return ambiencePlayer;
  try {
    const p = createAudioPlayer(SOUNDS.casinoAmbience);
    p.loop = true;
    p.volume = 0;
    ambiencePlayer = p;
  } catch { ambiencePlayer = null; }
  return ambiencePlayer;
}

async function _startAmbienceInternal() {
  if (ambienceActive) return;
  if (!isMusicEnabled) return;
  const p = getOrCreateAmbience();
  if (!p) return;
  ambienceActive = true;
  await safe(async () => {
    p.volume = 0;
    p.play();
  });
  await fadePlayerTo(p, ambienceVolume);
}

async function _stopAmbienceInternal() {
  if (!ambiencePlayer || !ambienceActive) return;
  ambienceActive = false;
  const p = ambiencePlayer;
  await fadePlayerTo(p, 0);
  await safe(async () => { p.pause(); });
}

// Public ambience controls — serialized through `ambienceTransition` so a
// rapid sequence of menu↔game route changes can never overlap a fade-in with
// a fade-out on the same player.
async function startAmbience() {
  const prev = ambienceTransition ?? Promise.resolve();
  const next = prev.then(() => _startAmbienceInternal()).catch(() => {});
  ambienceTransition = next;
  await next;
  if (ambienceTransition === next) ambienceTransition = null;
}

async function stopAmbience() {
  const prev = ambienceTransition ?? Promise.resolve();
  const next = prev.then(() => _stopAmbienceInternal()).catch(() => {});
  ambienceTransition = next;
  await next;
  if (ambienceTransition === next) ambienceTransition = null;
}

// When set, the casino ambience layer is forced ON regardless of which music
// track is currently playing. Used during the Reto de Fichas run so the
// casino atmosphere bleeds under the in-game music for the whole match.
let forceAmbience = false;

async function syncAmbienceWithTrack(track: MusicTrack | null) {
  if (isMusicEnabled && (forceAmbience || track === "menu")) {
    await startAmbience();
  } else {
    await stopAmbience();
  }
}

export async function setForceAmbience(enabled: boolean): Promise<void> {
  if (forceAmbience === enabled) return;
  forceAmbience = enabled;
  await syncAmbienceWithTrack(currentTrack);
}

async function applyMusicTransition(track: MusicTrack, opts?: { sequential?: boolean }) {
  if (currentTrack === track && bgPlayer) {
    syncAmbienceWithTrack(track).catch(() => {});
    return;
  }
  if (!isMusicEnabled) return;

  const oldPlayer = bgPlayer;
  const newPlayer = getOrCreateTrackPlayer(track);

  // Sequential mode: fully fade out + pause the old track BEFORE starting the
  // new one. Used for ranked matchmaking → game so menu/search music never
  // overlaps the start of the game track.
  if (opts?.sequential) {
    if (oldPlayer && oldPlayer !== newPlayer) {
      await fadePlayerTo(oldPlayer, 0);
      await safe(async () => { oldPlayer.pause(); });
    }
    if (newPlayer) {
      await safe(async () => {
        newPlayer.volume = 0;
        newPlayer.play();
      });
      bgPlayer = newPlayer;
      currentTrack = track;
      await fadePlayerTo(newPlayer, musicVolume);
    }
    syncAmbienceWithTrack(track).catch(() => {});
    return;
  }

  // Default: true crossfade between persistent per-track players. Old player
  // is paused (NOT destroyed) so its position is preserved; next time we
  // switch back to it, playback resumes seamlessly from where it left off.
  if (newPlayer) {
    await safe(async () => {
      newPlayer.volume = 0;
      newPlayer.play();
    });
    bgPlayer = newPlayer;
    currentTrack = track;
  }
  await Promise.all([
    oldPlayer && oldPlayer !== newPlayer ? fadePlayerTo(oldPlayer, 0) : Promise.resolve(),
    newPlayer ? fadePlayerTo(newPlayer, musicVolume) : Promise.resolve(),
  ]);
  if (oldPlayer && oldPlayer !== newPlayer) {
    await safe(async () => { oldPlayer.pause(); });
  }
  syncAmbienceWithTrack(track).catch(() => {});
}

async function fadePlayerTo(player: any, targetVol: number) {
  const startVol = player.volume ?? 0;
  const stepDur = FADE_MS / FADE_STEPS;
  for (let i = 1; i <= FADE_STEPS; i++) {
    const t = i / FADE_STEPS;
    const v = startVol + (targetVol - startVol) * t;
    await safe(async () => { player.volume = Math.max(0, Math.min(1, v)); });
    await new Promise<void>((r) => setTimeout(r, stepDur));
  }
}

async function requestMusicTrack(track: MusicTrack, opts?: { sequential?: boolean }) {
  // Record the latest desired track
  lastRequestedTrack = track;
  pendingTrack = track;
  if (opts?.sequential) pendingSequential = true;

  // If a transition is already in progress, let it pick up pendingTrack when done
  if (transitionInProgress) return;

  transitionInProgress = true;
  try {
    // Keep processing until there's no more pending request
    while (pendingTrack !== null) {
      const target = pendingTrack;
      const seq = pendingSequential;
      pendingTrack = null;
      pendingSequential = false;
      await applyMusicTransition(target, { sequential: seq });
    }
  } finally {
    transitionInProgress = false;
  }
}

export async function startMenuMusic() {
  await requestMusicTrack("menu");
}

export async function startGameMusic(opts?: { sequential?: boolean }) {
  await requestMusicTrack("game", opts);
}

export async function startSearchMusic() {
  await requestMusicTrack("search");
}

// Per-mode in-game music routing. Until dedicated per-mode loops are
// produced, we re-use the existing two music tracks (game / search) to
// give high-stakes modes (Torneo, Ranked, Reto de Fichas) a more tense,
// suspenseful backdrop versus the standard game-music for casual modes.
//
// Goes through the same serialized requestMusicTrack pipeline as
// startGameMusic so transitions never overlap when modes switch.
const MODE_TO_MUSIC_TRACK: Record<string, MusicTrack> = {
  practice: "game",
  classic: "game",
  lightning: "game",
  challenge: "game",
  tournament: "search",
  ranked: "search",
  fichas: "search",
};

export async function startGameMusicForMode(
  modeId: string | undefined,
  opts?: { sequential?: boolean; isFichasRun?: boolean },
) {
  const key = opts?.isFichasRun ? "fichas" : (modeId ?? "classic");
  const track = MODE_TO_MUSIC_TRACK[key] ?? "game";
  await requestMusicTrack(track, opts);
}

async function _stopMusicInternal() {
  const player = bgPlayer;
  bgPlayer = null;
  currentTrack = null;
  await stopAmbience();
  if (!player) return;
  // Pause but DO NOT remove — we want to preserve playback position so
  // resuming the track later continues from the same point.
  await safe(async () => { player.pause(); });
}

export async function stopMusic() {
  pendingTrack = null; // Cancel any pending transition
  await _stopMusicInternal();
}

export async function resumeCurrentMusic() {
  if (!isMusicEnabled || !lastRequestedTrack) return;
  if (bgPlayer) return; // Already playing
  const track = lastRequestedTrack;
  await requestMusicTrack(track);
}

export async function pauseMusic() {
  if (!bgPlayer) return;
  await safe(async () => bgPlayer!.pause());
}

export async function resumeMusic() {
  if (!bgPlayer || !isMusicEnabled) return;
  await safe(async () => bgPlayer!.play());
}

export function getCurrentTrack(): MusicTrack | null {
  return currentTrack;
}

async function playSfx(key: SoundKey, volume?: number) {
  if (isSfxMuted) return;
  if (isBackgrounded) return;
  await safe(async () => {
    const player = getOrCreateSfx(key);
    player.volume = volume ?? sfxVolume;
    player.seekTo(0);
    player.play();
  });
}

export async function setAppBackgrounded(backgrounded: boolean) {
  isBackgrounded = backgrounded;
  if (backgrounded) {
    // Hard-stop every SFX player too so card sounds never bleed into the home screen
    for (const player of sfxPlayers.values()) {
      await safe(async () => { player.pause(); });
    }
    if (ambiencePlayer && ambienceActive) {
      await safe(async () => { ambiencePlayer!.pause(); });
    }
  } else {
    if (ambienceActive && ambiencePlayer && isMusicEnabled) {
      await safe(async () => { ambiencePlayer!.play(); });
    }
  }
}

function haptic(fn: () => Promise<void>) {
  if (Platform.OS !== "web" && isHapticEnabled) safe(fn);
}

// ─── Core card sounds ────────────────────────────────────────────────────────

export async function playCardFlip() {
  const volume = sfxVolume * (0.8 + Math.random() * 0.2);
  await playSfx("cardFlip", volume);
  haptic(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light));
}

export async function playCardDraw() {
  await playSfx("cardDraw");
  haptic(() => Haptics.selectionAsync());
}

export async function playCardWild() {
  await playSfx("wild");
  haptic(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium));
}

export async function playShuffle() {
  await playSfx("shuffle");
  haptic(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Heavy));
}

export async function playWin() {
  await playSfx("win");
  haptic(() => Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success));
}

export async function playLose() {
  await playSfx("lose");
  haptic(() => Haptics.notificationAsync(Haptics.NotificationFeedbackType.Error));
}

export async function playButton() {
  await playSfx("button", sfxVolume * 0.7);
  haptic(() => Haptics.selectionAsync());
}

export async function playSpeedTick() {
  await playSfx("button", sfxVolume * 0.45);
  haptic(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light));
}

export async function playError() {
  await playSfx("button", sfxVolume * 0.5);
  haptic(() => Haptics.notificationAsync(Haptics.NotificationFeedbackType.Warning));
}

export async function playAchievement() {
  await playSfx("win", sfxVolume * 0.9);
  haptic(async () => {
    await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    setTimeout(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium), 150);
  });
}

// ─── UI interaction sounds ───────────────────────────────────────────────────

export async function playTabSwitch() {
  await playSfx("button", sfxVolume * 0.5);
  haptic(() => Haptics.selectionAsync());
}

export async function playSelect() {
  await playSfx("cardFlip", sfxVolume * 0.6);
  haptic(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light));
}

export async function playEquip() {
  await playSfx("cardDraw", sfxVolume * 0.8);
  haptic(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium));
}

export async function playMenuOpen() {
  await playSfx("shuffle", sfxVolume * 0.4);
  haptic(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light));
}

// ─── Reward & progression sounds ─────────────────────────────────────────────

export async function playCoinEarn() {
  await playSfx("wild", sfxVolume * 0.6);
  haptic(() => Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success));
}

export async function playStreak() {
  await playSfx("win", sfxVolume * 0.7);
  setTimeout(() => playSfx("button", sfxVolume * 0.5).catch(() => {}), 180);
  haptic(async () => {
    await Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Heavy);
    setTimeout(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium), 120);
  });
}

export async function playDailyReward() {
  await playSfx("win");
  setTimeout(() => playSfx("wild", sfxVolume * 0.5).catch(() => {}), 250);
  haptic(async () => {
    await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    setTimeout(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Heavy), 200);
  });
}

export async function playLevelUp() {
  await playSfx("win");
  setTimeout(() => playSfx("win", sfxVolume * 0.6).catch(() => {}), 300);
  haptic(async () => {
    await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    setTimeout(() => Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success), 300);
  });
}

// ─── Game event sounds ────────────────────────────────────────────────────────

export async function playOcho() {
  await playSfx("wild");
  setTimeout(() => playSfx("cardFlip", sfxVolume * 0.7).catch(() => {}), 120);
  setTimeout(() => playSfx("win", sfxVolume * 0.5).catch(() => {}), 250);
  haptic(async () => {
    await Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Heavy);
    setTimeout(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium), 130);
    setTimeout(() => Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success), 260);
  });
}

export async function playSpecialCard() {
  await playSfx("cardDraw", sfxVolume * 0.9);
  haptic(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium));
}

export async function playBlockCard() {
  await playSfx("button", sfxVolume * 0.8);
  setTimeout(() => playSfx("button", sfxVolume * 0.5).catch(() => {}), 100);
  haptic(async () => {
    await Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Heavy);
    setTimeout(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light), 120);
  });
}

export async function playDrawPenalty() {
  await playSfx("cardDraw");
  setTimeout(() => playSfx("cardDraw", sfxVolume * 0.8).catch(() => {}), 90);
  setTimeout(() => playSfx("cardDraw", sfxVolume * 0.6).catch(() => {}), 180);
  haptic(async () => {
    await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Warning);
    setTimeout(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light), 100);
  });
}

export async function playReverseCard() {
  await playSfx("shuffle", sfxVolume * 0.6);
  haptic(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium));
}

export async function playCountdownBeep() {
  await playSfx("button", sfxVolume * 0.6);
  haptic(() => Haptics.selectionAsync());
}

export async function playMatchStart() {
  await playSfx("win", sfxVolume * 0.8);
  setTimeout(() => playSfx("cardFlip", sfxVolume * 0.6).catch(() => {}), 200);
  setTimeout(() => playSfx("wild", sfxVolume * 0.5).catch(() => {}), 400);
  haptic(async () => {
    await Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Heavy);
    setTimeout(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium), 200);
  });
}

export async function playEffectBurst() {
  await playSfx("wild", sfxVolume * 0.5);
  haptic(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light));
}

export async function playTimerWarning() {
  await playSfx("button", sfxVolume * 0.4);
  haptic(() => Haptics.selectionAsync());
}

export async function playJokerPlay() {
  await playSfx("wild");
  setTimeout(() => playSfx("wild", sfxVolume * 0.6).catch(() => {}), 150);
  haptic(async () => {
    await Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Heavy);
    setTimeout(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium), 150);
  });
}

export async function playInactivityWarning() {
  await playSfx("button", sfxVolume * 0.5);
  setTimeout(() => playSfx("button", sfxVolume * 0.4).catch(() => {}), 150);
  haptic(() => Haptics.notificationAsync(Haptics.NotificationFeedbackType.Warning));
}

// ─── New sound events ─────────────────────────────────────────────────────────

// Chest opening sounds (Task #83) — each rarity plays its own dedicated
// procedurally-generated waveform from assets/sounds/ so common, rare,
// magic, epic, event, fichas, giant, legendary, and supreme all sound
// distinct. Higher rarities use longer, brighter samples + heavier haptics
// to reinforce the premium feel of the redesigned chest opening modal.
type ChestRarity =
  | "common" | "rare" | "magic" | "epic"
  | "event" | "fichas" | "giant" | "legendary" | "supreme";

const CHEST_OPEN_SFX: Record<ChestRarity, { key: SoundKey; volume: number }> = {
  common:    { key: "chestOpenCommon",    volume: 0.75 },
  rare:      { key: "chestOpenRare",      volume: 0.85 },
  magic:     { key: "chestOpenMagic",     volume: 0.90 },
  epic:      { key: "chestOpenEpic",      volume: 0.95 },
  event:     { key: "chestOpenEvent",     volume: 0.90 },
  fichas:    { key: "chestOpenFichas",    volume: 0.85 },
  giant:     { key: "chestOpenGiant",     volume: 1.00 },
  legendary: { key: "chestOpenLegendary", volume: 1.00 },
  supreme:   { key: "chestOpenSupreme",   volume: 1.00 },
};

export async function playChestOpen(rarity: ChestRarity) {
  const cfg = CHEST_OPEN_SFX[rarity] ?? CHEST_OPEN_SFX.common;
  await playSfx(cfg.key, sfxVolume * cfg.volume);
  // Layered haptics: stronger / longer for higher rarities.
  if (rarity === "common" || rarity === "fichas") {
    haptic(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium));
  } else if (rarity === "rare" || rarity === "event") {
    haptic(async () => {
      await Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
      setTimeout(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light), 200);
    });
  } else if (rarity === "magic" || rarity === "epic") {
    haptic(async () => {
      await Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Heavy);
      setTimeout(() => Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success), 260);
    });
  } else {
    // giant / legendary / supreme — multi-pulse fanfare haptic
    haptic(async () => {
      await Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Heavy);
      setTimeout(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Heavy), 220);
      setTimeout(() => Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success), 480);
    });
  }
}

// Reward claim sound — for path/road/battle-pass tier claims.
export async function playRewardClaim() {
  await playSfx("win", sfxVolume * 0.85);
  setTimeout(() => playSfx("wild", sfxVolume * 0.5).catch(() => {}), 180);
  haptic(async () => {
    await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    setTimeout(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium), 150);
  });
}

export async function playLastCard() {
  await playSfx("wild", sfxVolume * 0.95);
  setTimeout(() => playSfx("win", sfxVolume * 0.5).catch(() => {}), 140);
  haptic(async () => {
    await Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Heavy);
    setTimeout(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium), 120);
  });
}

export async function playCombo() {
  await playSfx("wild", sfxVolume * 0.8);
  setTimeout(() => playSfx("cardFlip", sfxVolume * 0.7).catch(() => {}), 100);
  haptic(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium));
}

export async function playFriendRequest() {
  await playSfx("button", sfxVolume * 0.8);
  setTimeout(() => playSfx("button", sfxVolume * 0.6).catch(() => {}), 120);
  haptic(() => Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success));
}

export async function playInviteAccepted() {
  await playSfx("win", sfxVolume * 0.85);
  haptic(async () => {
    await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    setTimeout(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium), 150);
  });
}

export async function playDealCard() {
  await playSfx("cardFlip", sfxVolume * (0.5 + Math.random() * 0.3));
  haptic(() => Haptics.selectionAsync());
}

export async function playTension() {
  await playSfx("button", sfxVolume * 0.45);
  haptic(() => Haptics.selectionAsync());
}

// ─── Personality SFX (Task #67) ──────────────────────────────────────────────
// Each plays a unique procedurally-generated waveform from assets/sounds/,
// not a remix of existing card/button samples.

export async function playMockLaugh()      { await playSfx("mockLaugh",      sfxVolume * 0.85); }
export async function playApplause()       { await playSfx("applauseSfx",    sfxVolume * 0.75); }
export async function playCrowdGasp()      { await playSfx("crowdGasp",      sfxVolume * 0.85); }
export async function playDramaticDrum()   { await playSfx("dramaticDrum",   sfxVolume * 0.95); haptic(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Heavy)); }
export async function playBoo()            { await playSfx("booSfx",         sfxVolume * 0.85); }
export async function playCackle()         { await playSfx("cackleSfx",      sfxVolume * 0.85); }
export async function playVictoryFanfare() { await playSfx("victoryFanfare", sfxVolume * 0.95); haptic(() => Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success)); }

// ─── Premium feedback (Task #74) ──────────────────────────────────────────────

// Short premium UI click — used by usePressFeedback for main menu / shop / modal
// buttons. Does NOT haptic itself (the caller does, so haptic & sound stay
// independent of each other when the user disables only one).
export async function playPremiumClick() {
  await playSfx("clickPremium", sfxVolume * 0.6);
}

// Synthesized "Ocho Locos" voice cue. Gated by the dedicated
// `voiceFxEnabled` setting so users can keep SFX on while muting the voice.
// Includes a short cooldown so multiple emitters (e.g. ranked-win + rank-up
// promotion) firing in quick succession can't stack the same voice clip.
let lastOchoLocosVoiceAt = 0;
const OCHO_LOCOS_VOICE_COOLDOWN_MS = 2500;
export async function playOchoLocosVoice() {
  if (!isVoiceFxEnabled) return;
  const now = Date.now();
  if (now - lastOchoLocosVoiceAt < OCHO_LOCOS_VOICE_COOLDOWN_MS) return;
  lastOchoLocosVoiceAt = now;
  await playSfx("ochoLocosVoice", sfxVolume * 0.95);
}

// Premium logo stinger. Played once when the main menu first mounts (per
// app session) to give the brand a sonic identity, in the spirit of the
// Clash Royale boot sound. Respects the SFX toggle via `playSfx`. Includes
// a session-level guard so navigating back to the menu won't replay it
// during the same app launch (until next process restart).
let logoStingerPlayedThisSession = false;
let selectedLogoStingerId: LogoStingerId = DEFAULT_LOGO_STINGER_ID;

// Task #85 — runtime-loaded custom logo stinger (from a file:// URI). We keep
// the player cached so repeated previews / boot don't decode the file twice.
let customStingerUri: string | null = null;
let customStingerPlayer: AudioPlayer | null = null;
// Task #91 — saved custom clips are now real, pre-trimmed m4a files written
// to the document directory (the trim window is baked in by the server's
// ffmpeg endpoint at Save time). When customStingerIsTrimmedFile is true,
// playback just plays the file from the start and lets it end naturally.
// The start/end markers below are still applied (seek + scheduled pause)
// for legacy profiles created before #91 (where the file is the full
// untrimmed source) so they keep stopping at the 2-second budget.
let customStingerStartMs = 0;
let customStingerEndMs = CUSTOM_LOGO_STINGER_MAX_MS;
let customStingerIsTrimmedFile = false;
let customStingerStopTimer: ReturnType<typeof setTimeout> | null = null;

function sfxKeyForStinger(id: LogoStingerId): SoundKey {
  const entry = LOGO_STINGERS.find((s) => s.id === id);
  return entry?.sfxKey ?? "logoStingerCasino";
}

export function setLogoStingerId(id: LogoStingerId) {
  selectedLogoStingerId = id;
}

export function getLogoStingerId(): LogoStingerId {
  return selectedLogoStingerId;
}

// Task #85 — register/clear the URI of the user's custom intro clip. Pass
// null to drop the cached player (e.g. when the user removes their clip or
// picks a new file).
export function setCustomStingerUri(uri: string | null) {
  if (uri === customStingerUri) return;
  if (customStingerStopTimer) {
    clearTimeout(customStingerStopTimer);
    customStingerStopTimer = null;
  }
  if (customStingerPlayer) {
    try { customStingerPlayer.pause(); customStingerPlayer.remove(); } catch {}
    customStingerPlayer = null;
  }
  customStingerUri = uri;
}

export function getCustomStingerUri(): string | null {
  return customStingerUri;
}

function getOrCreateCustomStingerPlayer(): AudioPlayer | null {
  if (!customStingerUri) return null;
  if (customStingerPlayer) return customStingerPlayer;
  try {
    const p = createAudioPlayer({ uri: customStingerUri });
    p.volume = sfxVolume * 0.95;
    customStingerPlayer = p;
  } catch { customStingerPlayer = null; }
  return customStingerPlayer;
}

// Task #91 — register the trim markers for the saved custom clip. Post-#91
// callers always pass isTrimmedFile=true with 0..trimmedDurationMs (the file
// IS the trimmed clip, so playback skips the seek + scheduled pause). Legacy
// callers (or boot-time hydration of a pre-#91 profile) leave isTrimmedFile
// undefined / false; we keep the window length capped at the 2-second budget
// so the legacy safety stop never exceeds it.
export function setCustomStingerTrim(startMs: number, endMs: number, isTrimmedFile?: boolean) {
  const a = Math.max(0, Math.floor(startMs));
  const b = Math.max(a, Math.floor(endMs));
  customStingerStartMs = a;
  customStingerEndMs = Math.min(b, a + CUSTOM_LOGO_STINGER_MAX_MS);
  customStingerIsTrimmedFile = !!isTrimmedFile;
}

// Task #87 — preview an arbitrary [startMs, endMs] window of a draft clip
// (the user's pick before they've committed to Save). Owned end-to-end by the
// audio manager so the trim modal doesn't have to manage its own AudioPlayer:
// it caches one player per URI, scrubs to startMs, and schedules a pause at
// endMs. Bypasses the SFX mute toggle on purpose — the player tapped Preview.
let draftStingerPlayer: AudioPlayer | null = null;
let draftStingerUri: string | null = null;
let draftStingerStopTimer: ReturnType<typeof setTimeout> | null = null;

export async function previewCustomStingerWindow(
  uri: string,
  startMs: number,
  endMs: number,
): Promise<boolean> {
  if (isBackgrounded) return false;
  stopCustomStingerWindowPreview();
  if (draftStingerPlayer && draftStingerUri !== uri) {
    try { draftStingerPlayer.remove(); } catch {}
    draftStingerPlayer = null;
  }
  if (!draftStingerPlayer) {
    try {
      draftStingerPlayer = createAudioPlayer({ uri });
      draftStingerUri = uri;
    } catch {
      draftStingerPlayer = null;
      draftStingerUri = null;
      return false;
    }
  }
  const start = Math.max(0, startMs);
  const windowMs = Math.max(50, Math.min(CUSTOM_LOGO_STINGER_MAX_MS, endMs - start));
  const p = draftStingerPlayer;
  await safe(async () => {
    p.volume = sfxVolume * 0.95;
    p.seekTo(start / 1000);
    p.play();
  });
  draftStingerStopTimer = setTimeout(() => {
    draftStingerStopTimer = null;
    try { p.pause(); } catch {}
  }, windowMs);
  return true;
}

export function stopCustomStingerWindowPreview() {
  if (draftStingerStopTimer) {
    clearTimeout(draftStingerStopTimer);
    draftStingerStopTimer = null;
  }
  if (draftStingerPlayer) {
    try { draftStingerPlayer.pause(); } catch {}
  }
}

export function releaseCustomStingerWindowPreview() {
  stopCustomStingerWindowPreview();
  if (draftStingerPlayer) {
    try { draftStingerPlayer.remove(); } catch {}
  }
  draftStingerPlayer = null;
  draftStingerUri = null;
}

async function playStingerById(id: LogoStingerId, volume: number): Promise<boolean> {
  if (isSfxMuted || isBackgrounded) return false;
  if (id === "custom") {
    const p = getOrCreateCustomStingerPlayer();
    if (!p) return false;
    // Task #91 — when isTrimmedFile=true the saved file IS the trimmed clip,
    // so just play from the start and let it end naturally. Pre-#91 (legacy)
    // profiles still need the seek + scheduled-pause trick to honour the
    // 2-second budget against a longer untrimmed source.
    if (customStingerStopTimer) {
      clearTimeout(customStingerStopTimer);
      customStingerStopTimer = null;
    }
    if (customStingerIsTrimmedFile) {
      await safe(async () => {
        p.volume = volume;
        p.seekTo(0);
        p.play();
      });
    } else {
      const startSec = customStingerStartMs / 1000;
      const windowMs = Math.min(
        CUSTOM_LOGO_STINGER_MAX_MS,
        Math.max(50, customStingerEndMs - customStingerStartMs),
      );
      await safe(async () => {
        p.volume = volume;
        p.seekTo(startSec);
        p.play();
      });
      customStingerStopTimer = setTimeout(() => {
        customStingerStopTimer = null;
        try { p.pause(); } catch {}
      }, windowMs);
    }
    return true;
  }
  await playSfx(sfxKeyForStinger(id), volume);
  return true;
}

export async function playLogoStinger() {
  if (logoStingerPlayedThisSession) return;
  logoStingerPlayedThisSession = true;
  // If the player picked the custom slot but their clip is missing (e.g. the
  // file was deleted), silently fall back to the default built-in stinger.
  const played = await playStingerById(selectedLogoStingerId, sfxVolume * 0.95);
  if (!played && selectedLogoStingerId === "custom") {
    await playStingerById(DEFAULT_LOGO_STINGER_ID, sfxVolume * 0.95);
  }
}

// Task #82 — preview a stinger from the Settings picker. Bypasses the
// once-per-session guard used by playLogoStinger so the user can audition
// every option, but still respects the SFX toggle and isBackgrounded
// check via playSfx.
export async function previewLogoStinger(id: LogoStingerId) {
  if (isSfxMuted) return;
  await playStingerById(id, sfxVolume * 0.95);
}

// ─── Settings ────────────────────────────────────────────────────────────────

export function syncSettings(
  musicEnabled: boolean,
  sfxEnabled: boolean,
  vibrationEnabled?: boolean,
  voiceFxEnabled?: boolean,
) {
  isMusicEnabled = musicEnabled;
  isSfxMuted = !sfxEnabled;
  if (vibrationEnabled !== undefined) isHapticEnabled = vibrationEnabled;
  if (voiceFxEnabled !== undefined) isVoiceFxEnabled = voiceFxEnabled;
  if (!musicEnabled && bgPlayer) {
    pauseMusic().catch(() => {});
    stopAmbience().catch(() => {});
  } else if (musicEnabled && bgPlayer) {
    resumeMusic().catch(() => {});
    if (currentTrack === "menu") startAmbience().catch(() => {});
  }
}

export function getMuted() { return isSfxMuted; }
export function getMusicEnabled() { return isMusicEnabled; }
// Centralized accessors for Task #74 — used by usePressFeedback so any
// premium press feedback respects the user's global vibration / voice
// toggles even before a syncSettings() round-trip.
export function getHapticEnabled() { return isHapticEnabled; }
export function getVoiceFxEnabled() { return isVoiceFxEnabled; }

export function setMusicVolume(vol: number) {
  musicVolume = Math.max(0, Math.min(1, vol));
  if (bgPlayer) safe(async () => { bgPlayer!.volume = musicVolume; });
}

export function setSfxVolume(vol: number) {
  sfxVolume = Math.max(0, Math.min(1, vol));
}

export async function cleanupAudio() {
  await _stopMusicInternal();
  for (const player of sfxPlayers.values()) {
    try { player.remove(); } catch {}
  }
  sfxPlayers.clear();
  for (const player of trackPlayers.values()) {
    try { player.pause(); player.remove(); } catch {}
  }
  trackPlayers.clear();
  if (ambiencePlayer) {
    try { ambiencePlayer.pause(); ambiencePlayer.remove(); } catch {}
    ambiencePlayer = null;
    ambienceActive = false;
  }
}
