export interface CpuProfile {
  name: string;
  avatarId: string;
  titleId: string;
  level: number;
  avatarColor: string;
  avatarIcon: string;
  photoUrl?: string;
}

export const CPU_PROFILES: CpuProfile[] = [
  { name: "CarlosM",       avatarId: "avatar_samurai",   titleId: "title_pro",          level: 14, avatarColor: "#E74C3C", avatarIcon: "cut",            photoUrl: "https://i.pravatar.cc/80?img=1" },
  { name: "Ana_Flores",    avatarId: "avatar_wizard",    titleId: "title_strategist",   level: 21, avatarColor: "#9B59B6", avatarIcon: "sparkles",       photoUrl: "https://i.pravatar.cc/80?img=2" },
  { name: "Dragón99",      avatarId: "avatar_dragon",    titleId: "title_ace",          level: 27, avatarColor: "#E67E22", avatarIcon: "flame",          photoUrl: "https://i.pravatar.cc/80?img=3" },
  { name: "MaestroK",      avatarId: "avatar_knight",    titleId: "title_grandmaster",  level: 42, avatarColor: "#95A5A6", avatarIcon: "shield",         photoUrl: "https://i.pravatar.cc/80?img=4" },
  { name: "SofiaCG",       avatarId: "avatar_scholar",   titleId: "title_regular",      level: 5,  avatarColor: "#4A90D9", avatarIcon: "book",           photoUrl: "https://i.pravatar.cc/80?img=5" },
  { name: "El_Fénix",      avatarId: "avatar_phoenix",   titleId: "title_legend",       level: 56, avatarColor: "#D4AF37", avatarIcon: "sunny",          photoUrl: "https://i.pravatar.cc/80?img=6" },
  { name: "Gladiator_X",   avatarId: "avatar_gladiator", titleId: "title_shark",        level: 18, avatarColor: "#C0392B", avatarIcon: "trophy",         photoUrl: "https://i.pravatar.cc/80?img=7" },
  { name: "CyberAce",      avatarId: "avatar_cyber",     titleId: "title_immortal",     level: 67, avatarColor: "#00D4FF", avatarIcon: "hardware-chip",  photoUrl: "https://i.pravatar.cc/80?img=8" },
  { name: "MiguelRdz",     avatarId: "avatar_merchant",  titleId: "title_rookie",       level: 3,  avatarColor: "#8B7355", avatarIcon: "bag",            photoUrl: "https://i.pravatar.cc/80?img=9" },
  { name: "ElSegador",     avatarId: "avatar_reaper",    titleId: "title_god",          level: 88, avatarColor: "#1a0020", avatarIcon: "moon" },
  { name: "Lupe_MX",       avatarId: "avatar_princess",  titleId: "title_hustler",      level: 11, avatarColor: "#E91E8C", avatarIcon: "heart",          photoUrl: "https://i.pravatar.cc/80?img=11" },
  { name: "xX_Dark",       avatarId: "avatar_ninja",     titleId: "title_phantom",      level: 33, avatarColor: "#1a1a2e", avatarIcon: "eye-off" },
  { name: "La_Pirata",     avatarId: "avatar_pirate",    titleId: "title_hustler",      level: 9,  avatarColor: "#2C3E50", avatarIcon: "skull",          photoUrl: "https://i.pravatar.cc/80?img=12" },
  { name: "ReyDelAs",      avatarId: "avatar_king",      titleId: "title_god",          level: 77, avatarColor: "#D4AF37", avatarIcon: "star",           photoUrl: "https://i.pravatar.cc/80?img=13" },
  { name: "Valentina.B",   avatarId: "avatar_scholar",   titleId: "title_queen",        level: 29, avatarColor: "#E91E8C", avatarIcon: "book",           photoUrl: "https://i.pravatar.cc/80?img=14" },
  { name: "ProGamer_Col",  avatarId: "avatar_cyber",     titleId: "title_pro",          level: 44, avatarColor: "#00BCD4", avatarIcon: "game-controller", photoUrl: "https://i.pravatar.cc/80?img=15" },
  { name: "Lalo777",       avatarId: "avatar_pirate",    titleId: "title_ace",          level: 7,  avatarColor: "#FF5722", avatarIcon: "skull",          photoUrl: "https://i.pravatar.cc/80?img=16" },
  { name: "IzabellaR",     avatarId: "avatar_princess",  titleId: "title_queen",        level: 38, avatarColor: "#AD1457", avatarIcon: "heart",          photoUrl: "https://i.pravatar.cc/80?img=17" },
  { name: "TitoLoco",      avatarId: "avatar_jester",    titleId: "title_joker",        level: 22, avatarColor: "#FF6F00", avatarIcon: "happy",          photoUrl: "https://i.pravatar.cc/80?img=18" },
  { name: "NightWolf",     avatarId: "avatar_wolf",      titleId: "title_phantom",      level: 51, avatarColor: "#37474F", avatarIcon: "moon",           photoUrl: "https://i.pravatar.cc/80?img=19" },
  { name: "Camila_BR",     avatarId: "avatar_wizard",    titleId: "title_regular",      level: 6,  avatarColor: "#7B1FA2", avatarIcon: "sparkles",       photoUrl: "https://i.pravatar.cc/80?img=20" },
  { name: "ElVaquero",     avatarId: "avatar_cowboy",    titleId: "title_veteran",      level: 35, avatarColor: "#795548", avatarIcon: "bonfire",        photoUrl: "https://i.pravatar.cc/80?img=21" },
  { name: "ShadowJack",    avatarId: "avatar_ninja",     titleId: "title_phantom",      level: 60, avatarColor: "#212121", avatarIcon: "eye-off" },
  { name: "RosaLeal",      avatarId: "avatar_scholar",   titleId: "title_regular",      level: 2,  avatarColor: "#F48FB1", avatarIcon: "book",           photoUrl: "https://i.pravatar.cc/80?img=22" },
  { name: "Chente_PE",     avatarId: "avatar_merchant",  titleId: "title_veteran",      level: 19, avatarColor: "#A1887F", avatarIcon: "bag",            photoUrl: "https://i.pravatar.cc/80?img=23" },
  { name: "DiamondLady",   avatarId: "avatar_princess",  titleId: "title_legend",       level: 72, avatarColor: "#B39DDB", avatarIcon: "diamond",        photoUrl: "https://i.pravatar.cc/80?img=24" },
  { name: "ZeroEight",     avatarId: "avatar_robot",     titleId: "title_immortal",     level: 83, avatarColor: "#78909C", avatarIcon: "hardware-chip",  photoUrl: "https://i.pravatar.cc/80?img=25" },
  { name: "JuanPaulo",     avatarId: "avatar_knight",    titleId: "title_pro",          level: 16, avatarColor: "#546E7A", avatarIcon: "shield",         photoUrl: "https://i.pravatar.cc/80?img=26" },
  { name: "Mariposa99",    avatarId: "avatar_fairy",     titleId: "title_queen",        level: 31, avatarColor: "#F06292", avatarIcon: "flower",         photoUrl: "https://i.pravatar.cc/80?img=27" },
  { name: "OscarVega",     avatarId: "avatar_merchant",  titleId: "title_veteran",      level: 24, avatarColor: "#8D6E63", avatarIcon: "bag",            photoUrl: "https://i.pravatar.cc/80?img=28" },
  { name: "Destroyer",     avatarId: "avatar_gladiator", titleId: "title_shark",        level: 65, avatarColor: "#B71C1C", avatarIcon: "trophy",         photoUrl: "https://i.pravatar.cc/80?img=29" },
  { name: "AlejandrA",     avatarId: "avatar_wizard",    titleId: "title_ace",          level: 13, avatarColor: "#6A1B9A", avatarIcon: "sparkles",       photoUrl: "https://i.pravatar.cc/80?img=30" },
  { name: "HeroArg",       avatarId: "avatar_phoenix",   titleId: "title_legend",       level: 49, avatarColor: "#F57F17", avatarIcon: "sunny",          photoUrl: "https://i.pravatar.cc/80?img=31" },
  { name: "TigresNL",      avatarId: "avatar_tiger",     titleId: "title_hustler",      level: 8,  avatarColor: "#E65100", avatarIcon: "paw",            photoUrl: "https://i.pravatar.cc/80?img=32" },
  { name: "GhostCard",     avatarId: "avatar_ninja",     titleId: "title_phantom",      level: 57, avatarColor: "#ECEFF1", avatarIcon: "eye-off" },
  { name: "LuisFco",       avatarId: "avatar_samurai",   titleId: "title_pro",          level: 26, avatarColor: "#1565C0", avatarIcon: "cut",            photoUrl: "https://i.pravatar.cc/80?img=33" },
  { name: "AzulCielo",     avatarId: "avatar_fairy",     titleId: "title_queen",        level: 17, avatarColor: "#0288D1", avatarIcon: "flower",         photoUrl: "https://i.pravatar.cc/80?img=34" },
  { name: "PabloEsco",     avatarId: "avatar_merchant",  titleId: "title_grandmaster",  level: 71, avatarColor: "#4E342E", avatarIcon: "bag",            photoUrl: "https://i.pravatar.cc/80?img=35" },
  { name: "AlmaRoja",      avatarId: "avatar_phoenix",   titleId: "title_legend",       level: 44, avatarColor: "#C62828", avatarIcon: "flame",          photoUrl: "https://i.pravatar.cc/80?img=36" },
  { name: "ElRuido",       avatarId: "avatar_jester",    titleId: "title_joker",        level: 12, avatarColor: "#FDD835", avatarIcon: "musical-notes",  photoUrl: "https://i.pravatar.cc/80?img=37" },
  { name: "Bruninha_SP",   avatarId: "avatar_princess",  titleId: "title_queen",        level: 23, avatarColor: "#F8BBD0", avatarIcon: "heart",          photoUrl: "https://i.pravatar.cc/80?img=38" },
  { name: "MatadorX",      avatarId: "avatar_gladiator", titleId: "title_ace",          level: 40, avatarColor: "#D32F2F", avatarIcon: "trophy",         photoUrl: "https://i.pravatar.cc/80?img=39" },
  { name: "CodeNinja",     avatarId: "avatar_cyber",     titleId: "title_immortal",     level: 79, avatarColor: "#00E5FF", avatarIcon: "code-slash",     photoUrl: "https://i.pravatar.cc/80?img=40" },
  { name: "DiegoR",        avatarId: "avatar_knight",    titleId: "title_pro",          level: 30, avatarColor: "#283593", avatarIcon: "shield",         photoUrl: "https://i.pravatar.cc/80?img=41" },
  { name: "MariaJose",     avatarId: "avatar_scholar",   titleId: "title_regular",      level: 4,  avatarColor: "#F06292", avatarIcon: "book",           photoUrl: "https://i.pravatar.cc/80?img=42" },
  { name: "Terremoto",     avatarId: "avatar_dragon",    titleId: "title_shark",        level: 66, avatarColor: "#BF360C", avatarIcon: "flame",          photoUrl: "https://i.pravatar.cc/80?img=43" },
  { name: "ElOso_MX",      avatarId: "avatar_bear",      titleId: "title_veteran",      level: 34, avatarColor: "#6D4C41", avatarIcon: "paw",            photoUrl: "https://i.pravatar.cc/80?img=44" },
  { name: "QuickShot",     avatarId: "avatar_ninja",     titleId: "title_ace",          level: 58, avatarColor: "#263238", avatarIcon: "flash",          photoUrl: "https://i.pravatar.cc/80?img=45" },
  { name: "JulioMar",      avatarId: "avatar_cowboy",    titleId: "title_pro",          level: 20, avatarColor: "#8D6E63", avatarIcon: "bonfire",        photoUrl: "https://i.pravatar.cc/80?img=46" },
  { name: "IsabelVidal",   avatarId: "avatar_fairy",     titleId: "title_queen",        level: 9,  avatarColor: "#E040FB", avatarIcon: "flower",         photoUrl: "https://i.pravatar.cc/80?img=47" },
  { name: "KingCobra",     avatarId: "avatar_dragon",    titleId: "title_god",          level: 92, avatarColor: "#1B5E20", avatarIcon: "flame",          photoUrl: "https://i.pravatar.cc/80?img=48" },
  { name: "FernandezJ",    avatarId: "avatar_merchant",  titleId: "title_veteran",      level: 28, avatarColor: "#5D4037", avatarIcon: "bag",            photoUrl: "https://i.pravatar.cc/80?img=49" },
  { name: "ViperZ",        avatarId: "avatar_ninja",     titleId: "title_phantom",      level: 74, avatarColor: "#004D40", avatarIcon: "eye-off" },
  { name: "NataliaQ",      avatarId: "avatar_princess",  titleId: "title_queen",        level: 15, avatarColor: "#AD1457", avatarIcon: "heart",          photoUrl: "https://i.pravatar.cc/80?img=50" },
  { name: "EduardoP",      avatarId: "avatar_gladiator", titleId: "title_pro",          level: 37, avatarColor: "#880E4F", avatarIcon: "trophy",         photoUrl: "https://i.pravatar.cc/80?img=51" },
  { name: "Luna_AR",       avatarId: "avatar_wizard",    titleId: "title_strategist",   level: 43, avatarColor: "#7C4DFF", avatarIcon: "sparkles",       photoUrl: "https://i.pravatar.cc/80?img=52" },
  { name: "Lobezno_MX",    avatarId: "avatar_wolf",      titleId: "title_shark",        level: 61, avatarColor: "#455A64", avatarIcon: "moon",           photoUrl: "https://i.pravatar.cc/80?img=53" },
  { name: "BiancaFerro",   avatarId: "avatar_princess",  titleId: "title_regular",      level: 10, avatarColor: "#F48FB1", avatarIcon: "heart",          photoUrl: "https://i.pravatar.cc/80?img=54" },
  { name: "RicardoAP",     avatarId: "avatar_samurai",   titleId: "title_grandmaster",  level: 85, avatarColor: "#0D47A1", avatarIcon: "cut",            photoUrl: "https://i.pravatar.cc/80?img=55" },
  { name: "TormentaBR",    avatarId: "avatar_phoenix",   titleId: "title_legend",       level: 53, avatarColor: "#FF6F00", avatarIcon: "sunny",          photoUrl: "https://i.pravatar.cc/80?img=56" },
  { name: "LaGata",        avatarId: "avatar_cat",       titleId: "title_hustler",      level: 18, avatarColor: "#FFA726", avatarIcon: "paw",            photoUrl: "https://i.pravatar.cc/80?img=57" },
  { name: "CruzBlanca",    avatarId: "avatar_knight",    titleId: "title_veteran",      level: 32, avatarColor: "#E8EAF6", avatarIcon: "shield",         photoUrl: "https://i.pravatar.cc/80?img=58" },
  { name: "ElGigante",     avatarId: "avatar_gladiator", titleId: "title_immortal",     level: 69, avatarColor: "#880E4F", avatarIcon: "barbell",        photoUrl: "https://i.pravatar.cc/80?img=59" },
  { name: "Marisol_VE",    avatarId: "avatar_scholar",   titleId: "title_regular",      level: 7,  avatarColor: "#FF80AB", avatarIcon: "book",           photoUrl: "https://i.pravatar.cc/80?img=60" },
  { name: "HawkEye_CO",    avatarId: "avatar_archer",    titleId: "title_ace",          level: 46, avatarColor: "#1A237E", avatarIcon: "eye",            photoUrl: "https://i.pravatar.cc/80?img=61" },
  { name: "Sombra404",     avatarId: "avatar_ninja",     titleId: "title_phantom",      level: 80, avatarColor: "#212121", avatarIcon: "eye-off" },
  { name: "FatimaBZ",      avatarId: "avatar_fairy",     titleId: "title_queen",        level: 25, avatarColor: "#CE93D8", avatarIcon: "flower",         photoUrl: "https://i.pravatar.cc/80?img=62" },
  { name: "GordoFeliz",    avatarId: "avatar_jester",    titleId: "title_joker",        level: 11, avatarColor: "#FFCA28", avatarIcon: "happy",          photoUrl: "https://i.pravatar.cc/80?img=63" },
  { name: "SerpienteAZ",   avatarId: "avatar_dragon",    titleId: "title_god",          level: 96, avatarColor: "#00695C", avatarIcon: "flame",          photoUrl: "https://i.pravatar.cc/80?img=64" },
  { name: "ArmandoCL",     avatarId: "avatar_cowboy",    titleId: "title_veteran",      level: 39, avatarColor: "#6D4C41", avatarIcon: "bonfire",        photoUrl: "https://i.pravatar.cc/80?img=65" },
  { name: "IronFist",      avatarId: "avatar_gladiator", titleId: "title_shark",        level: 63, avatarColor: "#616161", avatarIcon: "trophy",         photoUrl: "https://i.pravatar.cc/80?img=66" },
  { name: "VeronicaMJ",    avatarId: "avatar_princess",  titleId: "title_queen",        level: 16, avatarColor: "#EC407A", avatarIcon: "heart",          photoUrl: "https://i.pravatar.cc/80?img=67" },
  { name: "ArkAngel_PE",   avatarId: "avatar_phoenix",   titleId: "title_legend",       level: 59, avatarColor: "#B0BEC5", avatarIcon: "sunny",          photoUrl: "https://i.pravatar.cc/80?img=68" },
  { name: "DarkMatter",    avatarId: "avatar_reaper",    titleId: "title_god",          level: 99, avatarColor: "#000000", avatarIcon: "skull" },
  { name: "ChicoGuapo",    avatarId: "avatar_merchant",  titleId: "title_hustler",      level: 13, avatarColor: "#A0522D", avatarIcon: "bag",            photoUrl: "https://i.pravatar.cc/80?img=69" },
  { name: "EstrellaBR",    avatarId: "avatar_fairy",     titleId: "title_queen",        level: 48, avatarColor: "#F3E5F5", avatarIcon: "flower",         photoUrl: "https://i.pravatar.cc/80?img=70" },
  { name: "LeoCasanova",   avatarId: "avatar_samurai",   titleId: "title_ace",          level: 36, avatarColor: "#1976D2", avatarIcon: "cut",            photoUrl: "https://i.pravatar.cc/80?img=10" },
  { name: "RíoNegro",      avatarId: "avatar_ninja",     titleId: "title_phantom",      level: 54, avatarColor: "#1A1A1A", avatarIcon: "eye-off" },
  { name: "PetraVidal",    avatarId: "avatar_scholar",   titleId: "title_strategist",   level: 41, avatarColor: "#AB47BC", avatarIcon: "book",           photoUrl: "https://i.pravatar.cc/80?img=20" },
  { name: "Trueno88",      avatarId: "avatar_dragon",    titleId: "title_shark",        level: 73, avatarColor: "#F57C00", avatarIcon: "thunderstorm",   photoUrl: "https://i.pravatar.cc/80?img=30" },
  { name: "ElMisterio",    avatarId: "avatar_reaper",    titleId: "title_legend",       level: 81, avatarColor: "#311B92", avatarIcon: "moon" },
  { name: "MarcosTQ",      avatarId: "avatar_knight",    titleId: "title_grandmaster",  level: 47, avatarColor: "#1565C0", avatarIcon: "shield",         photoUrl: "https://i.pravatar.cc/80?img=40" },
  { name: "Perla_GT",      avatarId: "avatar_princess",  titleId: "title_regular",      level: 8,  avatarColor: "#F48FB1", avatarIcon: "heart",          photoUrl: "https://i.pravatar.cc/80?img=50" },
  { name: "KingPin_MX",    avatarId: "avatar_king",      titleId: "title_god",          level: 90, avatarColor: "#B71C1C", avatarIcon: "crown",          photoUrl: "https://i.pravatar.cc/80?img=60" },
  { name: "FlipMaster",    avatarId: "avatar_jester",    titleId: "title_joker",        level: 22, avatarColor: "#E65100", avatarIcon: "shuffle",        photoUrl: "https://i.pravatar.cc/80?img=14" },
  { name: "ElenaK",        avatarId: "avatar_fairy",     titleId: "title_queen",        level: 35, avatarColor: "#CE93D8", avatarIcon: "flower",         photoUrl: "https://i.pravatar.cc/80?img=24" },
  { name: "CrimsonAce",    avatarId: "avatar_gladiator", titleId: "title_ace",          level: 62, avatarColor: "#C62828", avatarIcon: "trophy",         photoUrl: "https://i.pravatar.cc/80?img=34" },
  { name: "GatoNegro",     avatarId: "avatar_cat",       titleId: "title_phantom",      level: 45, avatarColor: "#212121", avatarIcon: "paw",            photoUrl: "https://i.pravatar.cc/80?img=44" },
  { name: "SandraVC",      avatarId: "avatar_scholar",   titleId: "title_regular",      level: 6,  avatarColor: "#FF80AB", avatarIcon: "book",           photoUrl: "https://i.pravatar.cc/80?img=54" },
  { name: "ElFurioso",     avatarId: "avatar_dragon",    titleId: "title_shark",        level: 68, avatarColor: "#BF360C", avatarIcon: "flame",          photoUrl: "https://i.pravatar.cc/80?img=64" },
  { name: "LuceroMJ",      avatarId: "avatar_princess",  titleId: "title_queen",        level: 19, avatarColor: "#AD1457", avatarIcon: "heart",          photoUrl: "https://i.pravatar.cc/80?img=16" },
  { name: "RenatoBH",      avatarId: "avatar_samurai",   titleId: "title_pro",          level: 33, avatarColor: "#283593", avatarIcon: "cut",            photoUrl: "https://i.pravatar.cc/80?img=26" },
  { name: "StormCloud",    avatarId: "avatar_wizard",    titleId: "title_immortal",     level: 87, avatarColor: "#4527A0", avatarIcon: "thunderstorm",   photoUrl: "https://i.pravatar.cc/80?img=36" },
  { name: "EsperanzaQ",    avatarId: "avatar_fairy",     titleId: "title_queen",        level: 14, avatarColor: "#F48FB1", avatarIcon: "flower",         photoUrl: "https://i.pravatar.cc/80?img=46" },
  { name: "ElPistolero",   avatarId: "avatar_cowboy",    titleId: "title_veteran",      level: 52, avatarColor: "#4E342E", avatarIcon: "bonfire",        photoUrl: "https://i.pravatar.cc/80?img=56" },
  { name: "SilverBlade",   avatarId: "avatar_ninja",     titleId: "title_ace",          level: 76, avatarColor: "#78909C", avatarIcon: "eye-off" },
  { name: "AndreaFR",      avatarId: "avatar_scholar",   titleId: "title_regular",      level: 5,  avatarColor: "#7E57C2", avatarIcon: "book",           photoUrl: "https://i.pravatar.cc/80?img=66" },
  { name: "ElPumaCol",     avatarId: "avatar_tiger",     titleId: "title_hustler",      level: 21, avatarColor: "#FF8F00", avatarIcon: "paw",            photoUrl: "https://i.pravatar.cc/80?img=18" },
  { name: "MoriscoX",      avatarId: "avatar_gladiator", titleId: "title_grandmaster",  level: 64, avatarColor: "#4A148C", avatarIcon: "trophy",         photoUrl: "https://i.pravatar.cc/80?img=28" },
  { name: "CristalMar",    avatarId: "avatar_princess",  titleId: "title_queen",        level: 28, avatarColor: "#B2EBF2", avatarIcon: "heart",          photoUrl: "https://i.pravatar.cc/80?img=38" },
  { name: "DraculoZ",      avatarId: "avatar_reaper",    titleId: "title_legend",       level: 84, avatarColor: "#880E4F", avatarIcon: "skull" },
  { name: "ValentinoR",    avatarId: "avatar_king",      titleId: "title_god",          level: 93, avatarColor: "#D4AF37", avatarIcon: "crown",          photoUrl: "https://i.pravatar.cc/80?img=48" },
  { name: "MariaFerreira", avatarId: "avatar_fairy",     titleId: "title_regular",      level: 12, avatarColor: "#EC407A", avatarIcon: "flower",         photoUrl: "https://i.pravatar.cc/80?img=58" },
  { name: "LoboSolitario", avatarId: "avatar_wolf",      titleId: "title_phantom",      level: 70, avatarColor: "#546E7A", avatarIcon: "moon",           photoUrl: "https://i.pravatar.cc/80?img=68" },
  { name: "JoseM_Chile",   avatarId: "avatar_merchant",  titleId: "title_pro",          level: 26, avatarColor: "#795548", avatarIcon: "bag",            photoUrl: "https://i.pravatar.cc/80?img=22" },
  { name: "Ariadne_MX",    avatarId: "avatar_wizard",    titleId: "title_strategist",   level: 39, avatarColor: "#9C27B0", avatarIcon: "sparkles",       photoUrl: "https://i.pravatar.cc/80?img=32" },
  { name: "Predator88",    avatarId: "avatar_dragon",    titleId: "title_immortal",     level: 95, avatarColor: "#212121", avatarIcon: "eye" },
];

export function getRandomCpuProfile(seed?: number): CpuProfile {
  const idx = seed !== undefined
    ? Math.abs(seed) % CPU_PROFILES.length
    : Math.floor(Math.random() * CPU_PROFILES.length);
  return CPU_PROFILES[idx];
}
