import { pickRivalProfiles } from "./rivalGenerator";

export interface CpuProfile {
  name: string;
  avatarId: string;
  titleId: string;
  level: number;
  avatarColor: string;
  avatarIcon: string;
  photoUrl?: string;
}

export const CPU_PROFILES: CpuProfile[] = [
  { name: "CarlosM",       avatarId: "avatar_samurai",   titleId: "title_pro",          level: 14, avatarColor: "#E74C3C", avatarIcon: "cut",            photoUrl: "https://i.pravatar.cc/80?img=1" },
  { name: "Ana_Flores",    avatarId: "avatar_wizard",    titleId: "title_strategist",   level: 21, avatarColor: "#9B59B6", avatarIcon: "sparkles",       photoUrl: "https://i.pravatar.cc/80?img=2" },
  { name: "Dragón99",      avatarId: "avatar_dragon",    titleId: "title_ace",          level: 27, avatarColor: "#E67E22", avatarIcon: "flame",          photoUrl: "https://i.pravatar.cc/80?img=3" },
  { name: "MaestroK",      avatarId: "avatar_knight",    titleId: "title_grandmaster",  level: 42, avatarColor: "#95A5A6", avatarIcon: "shield",         photoUrl: "https://i.pravatar.cc/80?img=4" },
  { name: "SofiaCG",       avatarId: "avatar_scholar",   titleId: "title_regular",      level: 5,  avatarColor: "#4A90D9", avatarIcon: "book",           photoUrl: "https://i.pravatar.cc/80?img=5" },
  { name: "El_Fénix",      avatarId: "avatar_phoenix",   titleId: "title_legend",       level: 56, avatarColor: "#D4AF37", avatarIcon: "sunny",          photoUrl: "https://i.pravatar.cc/80?img=6" },
  { name: "Gladiator_X",   avatarId: "avatar_gladiator", titleId: "title_shark",        level: 18, avatarColor: "#C0392B", avatarIcon: "trophy",         photoUrl: "https://i.pravatar.cc/80?img=7" },
  { name: "CyberAce",      avatarId: "avatar_cyber",     titleId: "title_immortal",     level: 67, avatarColor: "#00D4FF", avatarIcon: "hardware-chip",  photoUrl: "https://i.pravatar.cc/80?img=8" },
  { name: "MiguelRdz",     avatarId: "avatar_merchant",  titleId: "title_rookie",       level: 3,  avatarColor: "#8B7355", avatarIcon: "bag",            photoUrl: "https://i.pravatar.cc/80?img=9" },
  { name: "ElSegador",     avatarId: "avatar_reaper",    titleId: "title_god",          level: 88, avatarColor: "#1a0020", avatarIcon: "moon" },
  { name: "Lupe",       avatarId: "avatar_princess",  titleId: "title_hustler",      level: 11, avatarColor: "#E91E8C", avatarIcon: "heart",          photoUrl: "https://i.pravatar.cc/80?img=11" },
  { name: "xX_Dark",       avatarId: "avatar_ninja",     titleId: "title_phantom",      level: 33, avatarColor: "#1a1a2e", avatarIcon: "eye-off" },
  { name: "La_Pirata",     avatarId: "avatar_pirate",    titleId: "title_hustler",      level: 9,  avatarColor: "#2C3E50", avatarIcon: "skull",          photoUrl: "https://i.pravatar.cc/80?img=12" },
  { name: "ReyDelAs",      avatarId: "avatar_king",      titleId: "title_god",          level: 77, avatarColor: "#D4AF37", avatarIcon: "star",           photoUrl: "https://i.pravatar.cc/80?img=13" },
  { name: "Valentina.B",   avatarId: "avatar_scholar",   titleId: "title_queen",        level: 29, avatarColor: "#E91E8C", avatarIcon: "book",           photoUrl: "https://i.pravatar.cc/80?img=14" },
  { name: "ProGamer_Col",  avatarId: "avatar_cyber",     titleId: "title_pro",          level: 44, avatarColor: "#00BCD4", avatarIcon: "game-controller", photoUrl: "https://i.pravatar.cc/80?img=15" },
  { name: "Lalo777",       avatarId: "avatar_pirate",    titleId: "title_ace",          level: 7,  avatarColor: "#FF5722", avatarIcon: "skull",          photoUrl: "https://i.pravatar.cc/80?img=16" },
  { name: "IzabellaR",     avatarId: "avatar_princess",  titleId: "title_queen",        level: 38, avatarColor: "#AD1457", avatarIcon: "heart",          photoUrl: "https://i.pravatar.cc/80?img=17" },
  { name: "TitoLoco",      avatarId: "avatar_jester",    titleId: "title_joker",        level: 22, avatarColor: "#FF6F00", avatarIcon: "happy",          photoUrl: "https://i.pravatar.cc/80?img=18" },
  { name: "NightWolf",     avatarId: "avatar_wolf",      titleId: "title_phantom",      level: 51, avatarColor: "#37474F", avatarIcon: "moon",           photoUrl: "https://i.pravatar.cc/80?img=19" },
  { name: "Camila",     avatarId: "avatar_wizard",    titleId: "title_regular",      level: 6,  avatarColor: "#7B1FA2", avatarIcon: "sparkles",       photoUrl: "https://i.pravatar.cc/80?img=20" },
  { name: "ElVaquero",     avatarId: "avatar_cowboy",    titleId: "title_veteran",      level: 35, avatarColor: "#795548", avatarIcon: "bonfire",        photoUrl: "https://i.pravatar.cc/80?img=21" },
  { name: "ShadowJack",    avatarId: "avatar_ninja",     titleId: "title_phantom",      level: 60, avatarColor: "#212121", avatarIcon: "eye-off" },
  { name: "RosaLeal",      avatarId: "avatar_scholar",   titleId: "title_regular",      level: 2,  avatarColor: "#F48FB1", avatarIcon: "book",           photoUrl: "https://i.pravatar.cc/80?img=22" },
  { name: "Chente",     avatarId: "avatar_merchant",  titleId: "title_veteran",      level: 19, avatarColor: "#A1887F", avatarIcon: "bag",            photoUrl: "https://i.pravatar.cc/80?img=23" },
  { name: "DiamondLady",   avatarId: "avatar_princess",  titleId: "title_legend",       level: 72, avatarColor: "#B39DDB", avatarIcon: "diamond",        photoUrl: "https://i.pravatar.cc/80?img=24" },
  { name: "ZeroEight",     avatarId: "avatar_robot",     titleId: "title_immortal",     level: 83, avatarColor: "#78909C", avatarIcon: "hardware-chip",  photoUrl: "https://i.pravatar.cc/80?img=25" },
  { name: "JuanPaulo",     avatarId: "avatar_knight",    titleId: "title_pro",          level: 16, avatarColor: "#546E7A", avatarIcon: "shield",         photoUrl: "https://i.pravatar.cc/80?img=26" },
  { name: "Mariposa99",    avatarId: "avatar_fairy",     titleId: "title_queen",        level: 31, avatarColor: "#F06292", avatarIcon: "flower",         photoUrl: "https://i.pravatar.cc/80?img=27" },
  { name: "OscarVega",     avatarId: "avatar_merchant",  titleId: "title_veteran",      level: 24, avatarColor: "#8D6E63", avatarIcon: "bag",            photoUrl: "https://i.pravatar.cc/80?img=28" },
  { name: "Destroyer",     avatarId: "avatar_gladiator", titleId: "title_shark",        level: 65, avatarColor: "#B71C1C", avatarIcon: "trophy",         photoUrl: "https://i.pravatar.cc/80?img=29" },
  { name: "AlejandrA",     avatarId: "avatar_wizard",    titleId: "title_ace",          level: 13, avatarColor: "#6A1B9A", avatarIcon: "sparkles",       photoUrl: "https://i.pravatar.cc/80?img=30" },
  { name: "HeroArg",       avatarId: "avatar_phoenix",   titleId: "title_legend",       level: 49, avatarColor: "#F57F17", avatarIcon: "sunny",          photoUrl: "https://i.pravatar.cc/80?img=31" },
  { name: "TigresNL",      avatarId: "avatar_tiger",     titleId: "title_hustler",      level: 8,  avatarColor: "#E65100", avatarIcon: "paw",            photoUrl: "https://i.pravatar.cc/80?img=32" },
  { name: "GhostCard",     avatarId: "avatar_ninja",     titleId: "title_phantom",      level: 57, avatarColor: "#ECEFF1", avatarIcon: "eye-off" },
  { name: "LuisFco",       avatarId: "avatar_samurai",   titleId: "title_pro",          level: 26, avatarColor: "#1565C0", avatarIcon: "cut",            photoUrl: "https://i.pravatar.cc/80?img=33" },
  { name: "AzulCielo",     avatarId: "avatar_fairy",     titleId: "title_queen",        level: 17, avatarColor: "#0288D1", avatarIcon: "flower",         photoUrl: "https://i.pravatar.cc/80?img=34" },
  { name: "PabloEsco",     avatarId: "avatar_merchant",  titleId: "title_grandmaster",  level: 71, avatarColor: "#4E342E", avatarIcon: "bag",            photoUrl: "https://i.pravatar.cc/80?img=35" },
  { name: "AlmaRoja",      avatarId: "avatar_phoenix",   titleId: "title_legend",       level: 44, avatarColor: "#C62828", avatarIcon: "flame",          photoUrl: "https://i.pravatar.cc/80?img=36" },
  { name: "ElRuido",       avatarId: "avatar_jester",    titleId: "title_joker",        level: 12, avatarColor: "#FDD835", avatarIcon: "musical-notes",  photoUrl: "https://i.pravatar.cc/80?img=37" },
  { name: "Bruninha_SP",   avatarId: "avatar_princess",  titleId: "title_queen",        level: 23, avatarColor: "#F8BBD0", avatarIcon: "heart",          photoUrl: "https://i.pravatar.cc/80?img=38" },
  { name: "MatadorX",      avatarId: "avatar_gladiator", titleId: "title_ace",          level: 40, avatarColor: "#D32F2F", avatarIcon: "trophy",         photoUrl: "https://i.pravatar.cc/80?img=39" },
  { name: "CodeNinja",     avatarId: "avatar_cyber",     titleId: "title_immortal",     level: 79, avatarColor: "#00E5FF", avatarIcon: "code-slash",     photoUrl: "https://i.pravatar.cc/80?img=40" },
  { name: "DiegoR",        avatarId: "avatar_knight",    titleId: "title_pro",          level: 30, avatarColor: "#283593", avatarIcon: "shield",         photoUrl: "https://i.pravatar.cc/80?img=41" },
  { name: "MariaJose",     avatarId: "avatar_scholar",   titleId: "title_regular",      level: 4,  avatarColor: "#F06292", avatarIcon: "book",           photoUrl: "https://i.pravatar.cc/80?img=42" },
  { name: "Terremoto",     avatarId: "avatar_dragon",    titleId: "title_shark",        level: 66, avatarColor: "#BF360C", avatarIcon: "flame",          photoUrl: "https://i.pravatar.cc/80?img=43" },
  { name: "ElOso",      avatarId: "avatar_bear",      titleId: "title_veteran",      level: 34, avatarColor: "#6D4C41", avatarIcon: "paw",            photoUrl: "https://i.pravatar.cc/80?img=44" },
  { name: "QuickShot",     avatarId: "avatar_ninja",     titleId: "title_ace",          level: 58, avatarColor: "#263238", avatarIcon: "flash",          photoUrl: "https://i.pravatar.cc/80?img=45" },
  { name: "JulioMar",      avatarId: "avatar_cowboy",    titleId: "title_pro",          level: 20, avatarColor: "#8D6E63", avatarIcon: "bonfire",        photoUrl: "https://i.pravatar.cc/80?img=46" },
  { name: "IsabelVidal",   avatarId: "avatar_fairy",     titleId: "title_queen",        level: 9,  avatarColor: "#E040FB", avatarIcon: "flower",         photoUrl: "https://i.pravatar.cc/80?img=47" },
  { name: "KingCobra",     avatarId: "avatar_dragon",    titleId: "title_god",          level: 92, avatarColor: "#1B5E20", avatarIcon: "flame",          photoUrl: "https://i.pravatar.cc/80?img=48" },
  { name: "FernandezJ",    avatarId: "avatar_merchant",  titleId: "title_veteran",      level: 28, avatarColor: "#5D4037", avatarIcon: "bag",            photoUrl: "https://i.pravatar.cc/80?img=49" },
  { name: "ViperZ",        avatarId: "avatar_ninja",     titleId: "title_phantom",      level: 74, avatarColor: "#004D40", avatarIcon: "eye-off" },
  { name: "NataliaQ",      avatarId: "avatar_princess",  titleId: "title_queen",        level: 15, avatarColor: "#AD1457", avatarIcon: "heart",          photoUrl: "https://i.pravatar.cc/80?img=50" },
  { name: "EduardoP",      avatarId: "avatar_gladiator", titleId: "title_pro",          level: 37, avatarColor: "#880E4F", avatarIcon: "trophy",         photoUrl: "https://i.pravatar.cc/80?img=51" },
  { name: "Luna",       avatarId: "avatar_wizard",    titleId: "title_strategist",   level: 43, avatarColor: "#7C4DFF", avatarIcon: "sparkles",       photoUrl: "https://i.pravatar.cc/80?img=52" },
  { name: "Lobezno",    avatarId: "avatar_wolf",      titleId: "title_shark",        level: 61, avatarColor: "#455A64", avatarIcon: "moon",           photoUrl: "https://i.pravatar.cc/80?img=53" },
  { name: "BiancaFerro",   avatarId: "avatar_princess",  titleId: "title_regular",      level: 10, avatarColor: "#F48FB1", avatarIcon: "heart",          photoUrl: "https://i.pravatar.cc/80?img=54" },
  { name: "RicardoRex",     avatarId: "avatar_samurai",   titleId: "title_grandmaster",  level: 85, avatarColor: "#0D47A1", avatarIcon: "cut",            photoUrl: "https://i.pravatar.cc/80?img=55" },
  { name: "TormentaBR",    avatarId: "avatar_phoenix",   titleId: "title_legend",       level: 53, avatarColor: "#FF6F00", avatarIcon: "sunny",          photoUrl: "https://i.pravatar.cc/80?img=56" },
  { name: "LaGata",        avatarId: "avatar_cat",       titleId: "title_hustler",      level: 18, avatarColor: "#FFA726", avatarIcon: "paw",            photoUrl: "https://i.pravatar.cc/80?img=57" },
  { name: "CruzBlanca",    avatarId: "avatar_knight",    titleId: "title_veteran",      level: 32, avatarColor: "#E8EAF6", avatarIcon: "shield",         photoUrl: "https://i.pravatar.cc/80?img=58" },
  { name: "ElGigante",     avatarId: "avatar_gladiator", titleId: "title_immortal",     level: 69, avatarColor: "#880E4F", avatarIcon: "barbell",        photoUrl: "https://i.pravatar.cc/80?img=59" },
  { name: "Marisol",    avatarId: "avatar_scholar",   titleId: "title_regular",      level: 7,  avatarColor: "#FF80AB", avatarIcon: "book",           photoUrl: "https://i.pravatar.cc/80?img=60" },
  { name: "HawkEye",    avatarId: "avatar_archer",    titleId: "title_ace",          level: 46, avatarColor: "#1A237E", avatarIcon: "eye",            photoUrl: "https://i.pravatar.cc/80?img=61" },
  { name: "Sombra404",     avatarId: "avatar_ninja",     titleId: "title_phantom",      level: 80, avatarColor: "#212121", avatarIcon: "eye-off" },
  { name: "FatimaBZ",      avatarId: "avatar_fairy",     titleId: "title_queen",        level: 25, avatarColor: "#CE93D8", avatarIcon: "flower",         photoUrl: "https://i.pravatar.cc/80?img=62" },
  { name: "GordoFeliz",    avatarId: "avatar_jester",    titleId: "title_joker",        level: 11, avatarColor: "#FFCA28", avatarIcon: "happy",          photoUrl: "https://i.pravatar.cc/80?img=63" },
  { name: "SerpienteAZ",   avatarId: "avatar_dragon",    titleId: "title_god",          level: 96, avatarColor: "#00695C", avatarIcon: "flame",          photoUrl: "https://i.pravatar.cc/80?img=64" },
  { name: "ArmandoCL",     avatarId: "avatar_cowboy",    titleId: "title_veteran",      level: 39, avatarColor: "#6D4C41", avatarIcon: "bonfire",        photoUrl: "https://i.pravatar.cc/80?img=65" },
  { name: "IronFist",      avatarId: "avatar_gladiator", titleId: "title_shark",        level: 63, avatarColor: "#616161", avatarIcon: "trophy",         photoUrl: "https://i.pravatar.cc/80?img=66" },
  { name: "Veronica",    avatarId: "avatar_princess",  titleId: "title_queen",        level: 16, avatarColor: "#EC407A", avatarIcon: "heart",          photoUrl: "https://i.pravatar.cc/80?img=67" },
  { name: "ArkAngel",   avatarId: "avatar_phoenix",   titleId: "title_legend",       level: 59, avatarColor: "#B0BEC5", avatarIcon: "sunny",          photoUrl: "https://i.pravatar.cc/80?img=68" },
  { name: "DarkMatter",    avatarId: "avatar_reaper",    titleId: "title_god",          level: 99, avatarColor: "#000000", avatarIcon: "skull" },
  { name: "ChicoGuapo",    avatarId: "avatar_merchant",  titleId: "title_hustler",      level: 13, avatarColor: "#A0522D", avatarIcon: "bag",            photoUrl: "https://i.pravatar.cc/80?img=69" },
  { name: "EstrellaBR",    avatarId: "avatar_fairy",     titleId: "title_queen",        level: 48, avatarColor: "#F3E5F5", avatarIcon: "flower",         photoUrl: "https://i.pravatar.cc/80?img=70" },
  { name: "LeoCasanova",   avatarId: "avatar_samurai",   titleId: "title_ace",          level: 36, avatarColor: "#1976D2", avatarIcon: "cut",            photoUrl: "https://i.pravatar.cc/80?img=10" },
  { name: "RíoNegro",      avatarId: "avatar_ninja",     titleId: "title_phantom",      level: 54, avatarColor: "#1A1A1A", avatarIcon: "eye-off" },
  { name: "PetraVidal",    avatarId: "avatar_scholar",   titleId: "title_strategist",   level: 41, avatarColor: "#AB47BC", avatarIcon: "book",           photoUrl: "https://i.pravatar.cc/80?img=20" },
  { name: "Trueno88",      avatarId: "avatar_dragon",    titleId: "title_shark",        level: 73, avatarColor: "#F57C00", avatarIcon: "thunderstorm",   photoUrl: "https://i.pravatar.cc/80?img=30" },
  { name: "ElMisterio",    avatarId: "avatar_reaper",    titleId: "title_legend",       level: 81, avatarColor: "#311B92", avatarIcon: "moon" },
  { name: "MarcosTQ",      avatarId: "avatar_knight",    titleId: "title_grandmaster",  level: 47, avatarColor: "#1565C0", avatarIcon: "shield",         photoUrl: "https://i.pravatar.cc/80?img=40" },
  { name: "Perla",      avatarId: "avatar_princess",  titleId: "title_regular",      level: 8,  avatarColor: "#F48FB1", avatarIcon: "heart",          photoUrl: "https://i.pravatar.cc/80?img=50" },
  { name: "KingPin",    avatarId: "avatar_king",      titleId: "title_god",          level: 90, avatarColor: "#B71C1C", avatarIcon: "ribbon",         photoUrl: "https://i.pravatar.cc/80?img=60" },
  { name: "FlipMaster",    avatarId: "avatar_jester",    titleId: "title_joker",        level: 22, avatarColor: "#E65100", avatarIcon: "shuffle",        photoUrl: "https://i.pravatar.cc/80?img=14" },
  { name: "ElenaK",        avatarId: "avatar_fairy",     titleId: "title_queen",        level: 35, avatarColor: "#CE93D8", avatarIcon: "flower",         photoUrl: "https://i.pravatar.cc/80?img=24" },
  { name: "CrimsonAce",    avatarId: "avatar_gladiator", titleId: "title_ace",          level: 62, avatarColor: "#C62828", avatarIcon: "trophy",         photoUrl: "https://i.pravatar.cc/80?img=34" },
  { name: "GatoNegro",     avatarId: "avatar_cat",       titleId: "title_phantom",      level: 45, avatarColor: "#212121", avatarIcon: "paw",            photoUrl: "https://i.pravatar.cc/80?img=44" },
  { name: "SandraVC",      avatarId: "avatar_scholar",   titleId: "title_regular",      level: 6,  avatarColor: "#FF80AB", avatarIcon: "book",           photoUrl: "https://i.pravatar.cc/80?img=54" },
  { name: "ElFurioso",     avatarId: "avatar_dragon",    titleId: "title_shark",        level: 68, avatarColor: "#BF360C", avatarIcon: "flame",          photoUrl: "https://i.pravatar.cc/80?img=64" },
  { name: "Lucero",      avatarId: "avatar_princess",  titleId: "title_queen",        level: 19, avatarColor: "#AD1457", avatarIcon: "heart",          photoUrl: "https://i.pravatar.cc/80?img=16" },
  { name: "RenatoZ",      avatarId: "avatar_samurai",   titleId: "title_pro",          level: 33, avatarColor: "#283593", avatarIcon: "cut",            photoUrl: "https://i.pravatar.cc/80?img=26" },
  { name: "StormCloud",    avatarId: "avatar_wizard",    titleId: "title_immortal",     level: 87, avatarColor: "#4527A0", avatarIcon: "thunderstorm",   photoUrl: "https://i.pravatar.cc/80?img=36" },
  { name: "EsperanzaQ",    avatarId: "avatar_fairy",     titleId: "title_queen",        level: 14, avatarColor: "#F48FB1", avatarIcon: "flower",         photoUrl: "https://i.pravatar.cc/80?img=46" },
  { name: "ElPistolero",   avatarId: "avatar_cowboy",    titleId: "title_veteran",      level: 52, avatarColor: "#4E342E", avatarIcon: "bonfire",        photoUrl: "https://i.pravatar.cc/80?img=56" },
  { name: "SilverBlade",   avatarId: "avatar_ninja",     titleId: "title_ace",          level: 76, avatarColor: "#78909C", avatarIcon: "eye-off" },
  { name: "AndreaFR",      avatarId: "avatar_scholar",   titleId: "title_regular",      level: 5,  avatarColor: "#7E57C2", avatarIcon: "book",           photoUrl: "https://i.pravatar.cc/80?img=66" },
  { name: "ElPumaCol",     avatarId: "avatar_tiger",     titleId: "title_hustler",      level: 21, avatarColor: "#FF8F00", avatarIcon: "paw",            photoUrl: "https://i.pravatar.cc/80?img=18" },
  { name: "MoriscoX",      avatarId: "avatar_gladiator", titleId: "title_grandmaster",  level: 64, avatarColor: "#4A148C", avatarIcon: "trophy",         photoUrl: "https://i.pravatar.cc/80?img=28" },
  { name: "CristalMar",    avatarId: "avatar_princess",  titleId: "title_queen",        level: 28, avatarColor: "#B2EBF2", avatarIcon: "heart",          photoUrl: "https://i.pravatar.cc/80?img=38" },
  { name: "DraculoZ",      avatarId: "avatar_reaper",    titleId: "title_legend",       level: 84, avatarColor: "#880E4F", avatarIcon: "skull" },
  { name: "ValentinoR",    avatarId: "avatar_king",      titleId: "title_god",          level: 93, avatarColor: "#D4AF37", avatarIcon: "medal",          photoUrl: "https://i.pravatar.cc/80?img=48" },
  { name: "MariaFerreira", avatarId: "avatar_fairy",     titleId: "title_regular",      level: 12, avatarColor: "#EC407A", avatarIcon: "flower",         photoUrl: "https://i.pravatar.cc/80?img=58" },
  { name: "LoboSolitario", avatarId: "avatar_wolf",      titleId: "title_phantom",      level: 70, avatarColor: "#546E7A", avatarIcon: "moon",           photoUrl: "https://i.pravatar.cc/80?img=68" },
  { name: "JoseMAce",   avatarId: "avatar_merchant",  titleId: "title_pro",          level: 26, avatarColor: "#795548", avatarIcon: "bag",            photoUrl: "https://i.pravatar.cc/80?img=22" },
  { name: "Ariadne",    avatarId: "avatar_wizard",    titleId: "title_strategist",   level: 39, avatarColor: "#9C27B0", avatarIcon: "sparkles",       photoUrl: "https://i.pravatar.cc/80?img=32" },
  { name: "Predator88",    avatarId: "avatar_dragon",    titleId: "title_immortal",     level: 95, avatarColor: "#212121", avatarIcon: "eye" },
  // ─── Profiles 108-200 ───────────────────────────────────────────────────────
  { name: "XavierMtz",     avatarId: "avatar_knight",    titleId: "title_pro",          level: 22, avatarColor: "#1565C0", avatarIcon: "shield",         photoUrl: "https://i.pravatar.cc/80?img=71" },
  { name: "IsabelaMR",     avatarId: "avatar_wizard",    titleId: "title_regular",      level: 8,  avatarColor: "#9C27B0", avatarIcon: "sparkles",       photoUrl: "https://i.pravatar.cc/80?img=72" },
  { name: "CaioX",        avatarId: "avatar_samurai",   titleId: "title_ace",          level: 44, avatarColor: "#0D47A1", avatarIcon: "cut",            photoUrl: "https://i.pravatar.cc/80?img=73" },
  { name: "LarissaZ",     avatarId: "avatar_scholar",   titleId: "title_strategist",   level: 17, avatarColor: "#F06292", avatarIcon: "book",           photoUrl: "https://i.pravatar.cc/80?img=74" },
  { name: "RodrigoX",      avatarId: "avatar_pirate",    titleId: "title_hustler",      level: 31, avatarColor: "#37474F", avatarIcon: "skull",          photoUrl: "https://i.pravatar.cc/80?img=75" },
  { name: "BrunoRS",       avatarId: "avatar_gladiator", titleId: "title_grandmaster",  level: 58, avatarColor: "#B71C1C", avatarIcon: "trophy",         photoUrl: "https://i.pravatar.cc/80?img=76" },
  { name: "FernandaPA",    avatarId: "avatar_ninja",     titleId: "title_phantom",      level: 27, avatarColor: "#4527A0", avatarIcon: "eye-off",        photoUrl: "https://i.pravatar.cc/80?img=77" },
  { name: "GabrielPro",     avatarId: "avatar_dragon",    titleId: "title_shark",        level: 63, avatarColor: "#BF360C", avatarIcon: "flame",          photoUrl: "https://i.pravatar.cc/80?img=78" },
  { name: "JulianaNova",     avatarId: "avatar_phoenix",   titleId: "title_legend",       level: 41, avatarColor: "#FF6F00", avatarIcon: "sunny",          photoUrl: "https://i.pravatar.cc/80?img=79" },
  { name: "ThiagoWild",      avatarId: "avatar_cyber",     titleId: "title_immortal",     level: 82, avatarColor: "#00BCD4", avatarIcon: "hardware-chip",  photoUrl: "https://i.pravatar.cc/80?img=80" },
  { name: "CarolinaG",     avatarId: "avatar_valkyrie",  titleId: "title_warrior",      level: 36, avatarColor: "#F0E68C", avatarIcon: "person",         photoUrl: "https://i.pravatar.cc/80?img=1"  },
  { name: "MatheusKing",     avatarId: "avatar_titan",     titleId: "title_god",          level: 75, avatarColor: "#78909C", avatarIcon: "barbell",        photoUrl: "https://i.pravatar.cc/80?img=2"  },
  { name: "PriscilaX",    avatarId: "avatar_oracle",    titleId: "title_mastermind",   level: 49, avatarColor: "#7B1FA2", avatarIcon: "eye",            photoUrl: "https://i.pravatar.cc/80?img=3"  },
  { name: "FelipeZ",      avatarId: "avatar_berserker", titleId: "title_dark_lord",    level: 66, avatarColor: "#C62828", avatarIcon: "flash",          photoUrl: "https://i.pravatar.cc/80?img=4"  },
  { name: "SabrinaAce",     avatarId: "avatar_sorcerer",  titleId: "title_invincible",   level: 53, avatarColor: "#6A1B9A", avatarIcon: "planet",         photoUrl: "https://i.pravatar.cc/80?img=5"  },
  { name: "GustavoG",     avatarId: "avatar_assassin",  titleId: "title_phantom",      level: 39, avatarColor: "#212121", avatarIcon: "warning",        photoUrl: "https://i.pravatar.cc/80?img=6"  },
  { name: "TatianaRex",     avatarId: "avatar_guardian",  titleId: "title_noble",        level: 14, avatarColor: "#1565C0", avatarIcon: "shield-checkmark",photoUrl: "https://i.pravatar.cc/80?img=7" },
  { name: "DiegoAR2",      avatarId: "avatar_warlord",   titleId: "title_overlord",     level: 88, avatarColor: "#B71C1C", avatarIcon: "people",         photoUrl: "https://i.pravatar.cc/80?img=8"  },
  { name: "MonicaCO",      avatarId: "avatar_necromancer",titleId:"title_dark_lord",    level: 72, avatarColor: "#4A148C", avatarIcon: "skull",          photoUrl: "https://i.pravatar.cc/80?img=9"  },
  { name: "AndresSV",      avatarId: "avatar_druid",     titleId: "title_guardian_t",   level: 28, avatarColor: "#1B5E20", avatarIcon: "leaf",           photoUrl: "https://i.pravatar.cc/80?img=10" },
  { name: "KarenHN",       avatarId: "avatar_spy",       titleId: "title_rogue_t",      level: 21, avatarColor: "#37474F", avatarIcon: "eye-off",        photoUrl: "https://i.pravatar.cc/80?img=11" },
  { name: "JavierGT",      avatarId: "avatar_alchemist", titleId: "title_mastermind",   level: 45, avatarColor: "#F57F17", avatarIcon: "flask",          photoUrl: "https://i.pravatar.cc/80?img=12" },
  { name: "MarcelaEC",     avatarId: "avatar_vampire",   titleId: "title_immortal",     level: 61, avatarColor: "#880E4F", avatarIcon: "moon",           photoUrl: "https://i.pravatar.cc/80?img=13" },
  { name: "SebastianBO",   avatarId: "avatar_werewolf",  titleId: "title_dark_lord",    level: 34, avatarColor: "#37474F", avatarIcon: "alert",          photoUrl: "https://i.pravatar.cc/80?img=14" },
  { name: "VanesaPY",      avatarId: "avatar_trickster", titleId: "title_joker_t",      level: 16, avatarColor: "#FF8F00", avatarIcon: "happy",          photoUrl: "https://i.pravatar.cc/80?img=15" },
  { name: "FabioUY",       avatarId: "avatar_shaman",    titleId: "title_observer",     level: 30, avatarColor: "#4E342E", avatarIcon: "bonfire",        photoUrl: "https://i.pravatar.cc/80?img=16" },
  { name: "LuciaVE",       avatarId: "avatar_rogue",     titleId: "title_renegade",     level: 52, avatarColor: "#263238", avatarIcon: "eye-off",        photoUrl: "https://i.pravatar.cc/80?img=17" },
  { name: "EstebanCR",     avatarId: "avatar_ranger",    titleId: "title_hunter",       level: 23, avatarColor: "#2E7D32", avatarIcon: "arrow-forward",  photoUrl: "https://i.pravatar.cc/80?img=18" },
  { name: "NathaliePA",    avatarId: "avatar_paladin",   titleId: "title_noble",        level: 38, avatarColor: "#1565C0", avatarIcon: "shield",         photoUrl: "https://i.pravatar.cc/80?img=19" },
  { name: "IgnacioCU",     avatarId: "avatar_bard",      titleId: "title_dreamer",      level: 11, avatarColor: "#7B1FA2", avatarIcon: "musical-notes",  photoUrl: "https://i.pravatar.cc/80?img=20" },
  { name: "PaolaDO",       avatarId: "avatar_detective",  titleId: "title_strategist",  level: 47, avatarColor: "#4E342E", avatarIcon: "search",         photoUrl: "https://i.pravatar.cc/80?img=21" },
  { name: "DavidES",       avatarId: "avatar_corsair",   titleId: "title_outlaw",       level: 69, avatarColor: "#1A237E", avatarIcon: "boat",           photoUrl: "https://i.pravatar.cc/80?img=22" },
  { name: "MartaUS",       avatarId: "avatar_astrologer",titleId: "title_observer",     level: 26, avatarColor: "#4527A0", avatarIcon: "star",           photoUrl: "https://i.pravatar.cc/80?img=23" },
  { name: "CarlosB2",      avatarId: "avatar_beastmaster",titleId:"title_warrior",      level: 55, avatarColor: "#4E342E", avatarIcon: "paw",            photoUrl: "https://i.pravatar.cc/80?img=24" },
  { name: "AnaL2",         avatarId: "avatar_mystic",    titleId: "title_dreamer",      level: 19, avatarColor: "#9C27B0", avatarIcon: "help-circle",    photoUrl: "https://i.pravatar.cc/80?img=25" },
  { name: "OmarME",        avatarId: "avatar_bounty",    titleId: "title_hunter",       level: 43, avatarColor: "#5D4037", avatarIcon: "locate",         photoUrl: "https://i.pravatar.cc/80?img=26" },
  { name: "IsabelCH",      avatarId: "avatar_explorer",  titleId: "title_traveler",     level: 12, avatarColor: "#1565C0", avatarIcon: "compass",        photoUrl: "https://i.pravatar.cc/80?img=27" },
  { name: "PedroNA",       avatarId: "avatar_chef",      titleId: "title_collector",    level: 7,  avatarColor: "#FF8F00", avatarIcon: "restaurant",     photoUrl: "https://i.pravatar.cc/80?img=28" },
  { name: "YolandaVE2",    avatarId: "avatar_athlete",   titleId: "title_competitor",   level: 33, avatarColor: "#E64A19", avatarIcon: "fitness",        photoUrl: "https://i.pravatar.cc/80?img=29" },
  { name: "HugoCO",        avatarId: "avatar_pilot",     titleId: "title_drifter",      level: 57, avatarColor: "#0277BD", avatarIcon: "airplane",       photoUrl: "https://i.pravatar.cc/80?img=30" },
  { name: "MariangelaCO",  avatarId: "avatar_farmer",    titleId: "title_wanderer",     level: 9,  avatarColor: "#558B2F", avatarIcon: "leaf",           photoUrl: "https://i.pravatar.cc/80?img=31" },
  { name: "CristianEC",    avatarId: "avatar_smith",     titleId: "title_warrior",      level: 40, avatarColor: "#4E342E", avatarIcon: "hammer",         photoUrl: "https://i.pravatar.cc/80?img=32" },
  { name: "RaquelBO",      avatarId: "avatar_guard",     titleId: "title_guardian_t",   level: 18, avatarColor: "#546E7A", avatarIcon: "shield",         photoUrl: "https://i.pravatar.cc/80?img=33" },
  { name: "AlexPE",        avatarId: "avatar_scout",     titleId: "title_competitor",   level: 25, avatarColor: "#2E7D32", avatarIcon: "binoculars",     photoUrl: "https://i.pravatar.cc/80?img=34" },
  { name: "SilviaGT",      avatarId: "avatar_monk",      titleId: "title_observer",     level: 48, avatarColor: "#37474F", avatarIcon: "bookmarks",      photoUrl: "https://i.pravatar.cc/80?img=35" },
  { name: "RamonHN",       avatarId: "avatar_sailor",    titleId: "title_drifter",      level: 15, avatarColor: "#0277BD", avatarIcon: "boat",           photoUrl: "https://i.pravatar.cc/80?img=36" },
  { name: "TeresaSV",      avatarId: "avatar_miner",     titleId: "title_veteran",      level: 62, avatarColor: "#6D4C41", avatarIcon: "hammer",         photoUrl: "https://i.pravatar.cc/80?img=37" },
  { name: "ErnestoCR",     avatarId: "avatar_artist",    titleId: "title_dreamer",      level: 24, avatarColor: "#7B1FA2", avatarIcon: "color-palette",  photoUrl: "https://i.pravatar.cc/80?img=38" },
  { name: "DulcePR",       avatarId: "avatar_conqueror", titleId: "title_invincible",   level: 77, avatarColor: "#B71C1C", avatarIcon: "flag",           photoUrl: "https://i.pravatar.cc/80?img=39" },
  { name: "ErickCA",       avatarId: "avatar_archmage",  titleId: "title_transcendent", level: 91, avatarColor: "#4527A0", avatarIcon: "sparkles",       photoUrl: "https://i.pravatar.cc/80?img=40" },
  { name: "NancyMX2",      avatarId: "avatar_templar",   titleId: "title_noble",        level: 29, avatarColor: "#1565C0", avatarIcon: "shield-checkmark",photoUrl:"https://i.pravatar.cc/80?img=41"},
  { name: "OscarB2",       avatarId: "avatar_harbinger", titleId: "title_absolute",     level: 84, avatarColor: "#880E4F", avatarIcon: "warning",        photoUrl: "https://i.pravatar.cc/80?img=42" },
  { name: "CeciliaAR2",    avatarId: "avatar_wraith",    titleId: "title_phantom",      level: 46, avatarColor: "#4A148C", avatarIcon: "cloud",          photoUrl: "https://i.pravatar.cc/80?img=43" },
  { name: "JorgeVE2",      avatarId: "avatar_sentinel",  titleId: "title_guardian_t",   level: 37, avatarColor: "#37474F", avatarIcon: "eye",            photoUrl: "https://i.pravatar.cc/80?img=44" },
  { name: "MiguelCO2",     avatarId: "avatar_vanguard",  titleId: "title_vanguard_t",   level: 54, avatarColor: "#E64A19", avatarIcon: "flag",           photoUrl: "https://i.pravatar.cc/80?img=45" },
  { name: "PaolaUS",       avatarId: "avatar_sharpshooter",titleId:"title_predator",   level: 68, avatarColor: "#212121", avatarIcon: "locate",         photoUrl: "https://i.pravatar.cc/80?img=46" },
  { name: "MarceloBR2",    avatarId: "avatar_overlord_av",titleId:"title_overlord",    level: 79, avatarColor: "#880E4F", avatarIcon: "people",         photoUrl: "https://i.pravatar.cc/80?img=47" },
  { name: "AmandaZ",      avatarId: "avatar_demigod",   titleId: "title_absolute",     level: 86, avatarColor: "#D4AF37", avatarIcon: "flash",          photoUrl: "https://i.pravatar.cc/80?img=48" },
  { name: "LeonardoSP2",   avatarId: "avatar_entity",    titleId: "title_transcendent", level: 93, avatarColor: "#000000", avatarIcon: "help-circle" },
  { name: "ReginaKing",      avatarId: "avatar_titan_god", titleId: "title_god",          level: 97, avatarColor: "#C0C0C0", avatarIcon: "barbell",        photoUrl: "https://i.pravatar.cc/80?img=50" },
  { name: "GerardoMX2",    avatarId: "avatar_emperor",   titleId: "title_absolute",     level: 89, avatarColor: "#D4AF37", avatarIcon: "ribbon",         photoUrl: "https://i.pravatar.cc/80?img=51" },
  { name: "FrancescaIT",   avatarId: "avatar_celestial", titleId: "title_transcendent", level: 73, avatarColor: "#4FC3F7", avatarIcon: "planet",         photoUrl: "https://i.pravatar.cc/80?img=52" },
  { name: "RodrigoBO2",    avatarId: "avatar_chaos",     titleId: "title_renegade",     level: 60, avatarColor: "#A855F7", avatarIcon: "infinite",       photoUrl: "https://i.pravatar.cc/80?img=53" },
  { name: "ElenaAR",       avatarId: "avatar_knight",    titleId: "title_wanderer",     level: 5,  avatarColor: "#546E7A", avatarIcon: "shield",         photoUrl: "https://i.pravatar.cc/80?img=54" },
  { name: "AntonioX",     avatarId: "avatar_wizard",    titleId: "title_grandmaster",  level: 76, avatarColor: "#6A1B9A", avatarIcon: "sparkles",       photoUrl: "https://i.pravatar.cc/80?img=55" },
  { name: "RosalinaCO2",   avatarId: "avatar_samurai",   titleId: "title_strategist",   level: 32, avatarColor: "#880E4F", avatarIcon: "cut",            photoUrl: "https://i.pravatar.cc/80?img=56" },
  { name: "FreddyVE",      avatarId: "avatar_pirate",    titleId: "title_shark",        level: 20, avatarColor: "#4E342E", avatarIcon: "skull",          photoUrl: "https://i.pravatar.cc/80?img=57" },
  { name: "EsmeraldaPE2",  avatarId: "avatar_dragon",    titleId: "title_legend",       level: 64, avatarColor: "#1B5E20", avatarIcon: "flame",          photoUrl: "https://i.pravatar.cc/80?img=58" },
  { name: "BenjaminCL2",   avatarId: "avatar_cyber",     titleId: "title_immortal",     level: 85, avatarColor: "#00E5FF", avatarIcon: "hardware-chip",  photoUrl: "https://i.pravatar.cc/80?img=59" },
  { name: "ValeriaEC2",    avatarId: "avatar_gladiator", titleId: "title_ace",          level: 43, avatarColor: "#D32F2F", avatarIcon: "trophy",         photoUrl: "https://i.pravatar.cc/80?img=60" },
  { name: "HectorMX3",     avatarId: "avatar_ninja",     titleId: "title_predator",     level: 57, avatarColor: "#1A1A2E", avatarIcon: "eye-off" },
  { name: "MarleneX",     avatarId: "avatar_phoenix",   titleId: "title_comeback",     level: 48, avatarColor: "#C62828", avatarIcon: "sunny",          photoUrl: "https://i.pravatar.cc/80?img=62" },
  { name: "AlbertoGT2",    avatarId: "avatar_reaper",    titleId: "title_dark_lord",    level: 81, avatarColor: "#4A148C", avatarIcon: "skull" },
  { name: "SofiaUS",       avatarId: "avatar_king",      titleId: "title_god",          level: 90, avatarColor: "#D4AF37", avatarIcon: "star",           photoUrl: "https://i.pravatar.cc/80?img=64" },
  { name: "PabloCO3",      avatarId: "avatar_oracle",    titleId: "title_strategist",   level: 36, avatarColor: "#7C4DFF", avatarIcon: "eye",            photoUrl: "https://i.pravatar.cc/80?img=65" },
  { name: "CelesteMX",     avatarId: "avatar_valkyrie",  titleId: "title_invincible",   level: 52, avatarColor: "#F0E68C", avatarIcon: "person",         photoUrl: "https://i.pravatar.cc/80?img=66" },
  { name: "GabrielBR3",    avatarId: "avatar_berserker", titleId: "title_warrior",      level: 67, avatarColor: "#D32F2F", avatarIcon: "flash",          photoUrl: "https://i.pravatar.cc/80?img=67" },
  { name: "IsabelaStar",     avatarId: "avatar_sorcerer",  titleId: "title_mastermind",   level: 74, avatarColor: "#6A1B9A", avatarIcon: "planet",         photoUrl: "https://i.pravatar.cc/80?img=68" },
  { name: "RodolfoCL2",    avatarId: "avatar_warlord",   titleId: "title_overlord",     level: 96, avatarColor: "#880E4F", avatarIcon: "people",         photoUrl: "https://i.pravatar.cc/80?img=69" },
  { name: "ElviraES",      avatarId: "avatar_assassin",  titleId: "title_phantom",      level: 40, avatarColor: "#212121", avatarIcon: "warning",        photoUrl: "https://i.pravatar.cc/80?img=70" },
  // ─── Profiles 201-300 ───────────────────────────────────────────────────────
  { name: "JuanDMX",       avatarId: "avatar_guardian",  titleId: "title_warrior",      level: 18, avatarColor: "#1565C0", avatarIcon: "shield-checkmark",photoUrl:"https://i.pravatar.cc/80?img=71"},
  { name: "PenelopeCL",    avatarId: "avatar_mystic",    titleId: "title_observer",     level: 29, avatarColor: "#9C27B0", avatarIcon: "help-circle",    photoUrl: "https://i.pravatar.cc/80?img=72" },
  { name: "ClaudiaVE3",    avatarId: "avatar_spy",       titleId: "title_rogue_t",      level: 44, avatarColor: "#263238", avatarIcon: "eye-off",        photoUrl: "https://i.pravatar.cc/80?img=73" },
  { name: "EnriqueBR4",    avatarId: "avatar_necromancer",titleId:"title_dark_lord",    level: 61, avatarColor: "#4A148C", avatarIcon: "skull",          photoUrl: "https://i.pravatar.cc/80?img=74" },
  { name: "MaellaAR3",     avatarId: "avatar_druid",     titleId: "title_collector",    level: 15, avatarColor: "#2E7D32", avatarIcon: "leaf",           photoUrl: "https://i.pravatar.cc/80?img=75" },
  { name: "JoelCO4",       avatarId: "avatar_alchemist", titleId: "title_trickster",    level: 38, avatarColor: "#F57F17", avatarIcon: "flask",          photoUrl: "https://i.pravatar.cc/80?img=76" },
  { name: "AlejandraHN2",  avatarId: "avatar_vampire",   titleId: "title_shadow2",      level: 55, avatarColor: "#880E4F", avatarIcon: "moon",           photoUrl: "https://i.pravatar.cc/80?img=77" },
  { name: "SantosGT3",     avatarId: "avatar_ranger",    titleId: "title_hunter",       level: 22, avatarColor: "#2E7D32", avatarIcon: "arrow-forward",  photoUrl: "https://i.pravatar.cc/80?img=78" },
  { name: "MiriamSV2",     avatarId: "avatar_paladin",   titleId: "title_vanguard_t",   level: 48, avatarColor: "#1565C0", avatarIcon: "shield",         photoUrl: "https://i.pravatar.cc/80?img=79" },
  { name: "SalvadorCR2",   avatarId: "avatar_bard",      titleId: "title_casual",       level: 10, avatarColor: "#7B1FA2", avatarIcon: "musical-notes",  photoUrl: "https://i.pravatar.cc/80?img=80" },
  { name: "VeraPA2",       avatarId: "avatar_detective",  titleId: "title_fox",         level: 34, avatarColor: "#4E342E", avatarIcon: "search",         photoUrl: "https://i.pravatar.cc/80?img=1"  },
  { name: "LuisCU2",       avatarId: "avatar_corsair",   titleId: "title_drifter",      level: 57, avatarColor: "#1A237E", avatarIcon: "boat",           photoUrl: "https://i.pravatar.cc/80?img=2"  },
  { name: "CarmenDO2",     avatarId: "avatar_astrologer",titleId: "title_dreamer",      level: 26, avatarColor: "#4527A0", avatarIcon: "star",           photoUrl: "https://i.pravatar.cc/80?img=3"  },
  { name: "JorgeMX4",      avatarId: "avatar_beastmaster",titleId:"title_competitor",   level: 41, avatarColor: "#4E342E", avatarIcon: "paw",            photoUrl: "https://i.pravatar.cc/80?img=4"  },
  { name: "GabriellaIT",   avatarId: "avatar_trickster", titleId: "title_joker_t",      level: 19, avatarColor: "#FF8F00", avatarIcon: "happy",          photoUrl: "https://i.pravatar.cc/80?img=5"  },
  { name: "MarcosCO5",     avatarId: "avatar_shaman",    titleId: "title_believer",     level: 32, avatarColor: "#5D4037", avatarIcon: "bonfire",        photoUrl: "https://i.pravatar.cc/80?img=6"  },
  { name: "AmeliaUS2",     avatarId: "avatar_rogue",     titleId: "title_maverick",     level: 46, avatarColor: "#37474F", avatarIcon: "eye-off",        photoUrl: "https://i.pravatar.cc/80?img=7"  },
  { name: "RicardoCL3",    avatarId: "avatar_werewolf",  titleId: "title_dark_lord",    level: 63, avatarColor: "#37474F", avatarIcon: "alert",          photoUrl: "https://i.pravatar.cc/80?img=8"  },
  { name: "IreneES2",      avatarId: "avatar_explorer",  titleId: "title_wanderer",     level: 13, avatarColor: "#0277BD", avatarIcon: "compass",        photoUrl: "https://i.pravatar.cc/80?img=9"  },
  { name: "FranciscoCO6",  avatarId: "avatar_chef",      titleId: "title_apprentice",   level: 8,  avatarColor: "#FF8F00", avatarIcon: "restaurant",     photoUrl: "https://i.pravatar.cc/80?img=10" },
  { name: "MercedesMX5",   avatarId: "avatar_athlete",   titleId: "title_drifter",      level: 25, avatarColor: "#E64A19", avatarIcon: "fitness",        photoUrl: "https://i.pravatar.cc/80?img=11" },
  { name: "BernardoPE3",   avatarId: "avatar_pilot",     titleId: "title_traveler",     level: 51, avatarColor: "#0277BD", avatarIcon: "airplane",       photoUrl: "https://i.pravatar.cc/80?img=12" },
  { name: "CeliaVE4",      avatarId: "avatar_farmer",    titleId: "title_survivor",     level: 7,  avatarColor: "#558B2F", avatarIcon: "leaf",           photoUrl: "https://i.pravatar.cc/80?img=13" },
  { name: "EmilioES3",     avatarId: "avatar_smith",     titleId: "title_challenger",   level: 37, avatarColor: "#37474F", avatarIcon: "hammer",         photoUrl: "https://i.pravatar.cc/80?img=14" },
  { name: "TerencioAR4",   avatarId: "avatar_guard",     titleId: "title_guardian_t",   level: 20, avatarColor: "#546E7A", avatarIcon: "shield",         photoUrl: "https://i.pravatar.cc/80?img=15" },
  { name: "RaquelMX6",     avatarId: "avatar_scout",     titleId: "title_rookie",       level: 3,  avatarColor: "#2E7D32", avatarIcon: "binoculars",     photoUrl: "https://i.pravatar.cc/80?img=16" },
  { name: "AlfredoGT4",    avatarId: "avatar_monk",      titleId: "title_believer",     level: 42, avatarColor: "#37474F", avatarIcon: "bookmarks",      photoUrl: "https://i.pravatar.cc/80?img=17" },
  { name: "SoniaSV3",      avatarId: "avatar_sailor",    titleId: "title_traveler",     level: 16, avatarColor: "#0277BD", avatarIcon: "boat",           photoUrl: "https://i.pravatar.cc/80?img=18" },
  { name: "PiotrPL",       avatarId: "avatar_miner",     titleId: "title_veteran",      level: 58, avatarColor: "#546E7A", avatarIcon: "hammer",         photoUrl: "https://i.pravatar.cc/80?img=19" },
  { name: "KatarzynaES",   avatarId: "avatar_artist",    titleId: "title_dreamer",      level: 27, avatarColor: "#F06292", avatarIcon: "color-palette",  photoUrl: "https://i.pravatar.cc/80?img=20" },
  { name: "MichaelUS2",    avatarId: "avatar_conqueror", titleId: "title_champion",     level: 71, avatarColor: "#B71C1C", avatarIcon: "flag",           photoUrl: "https://i.pravatar.cc/80?img=21" },
  { name: "JessicaUS",     avatarId: "avatar_archmage",  titleId: "title_grandmaster",  level: 84, avatarColor: "#4527A0", avatarIcon: "sparkles",       photoUrl: "https://i.pravatar.cc/80?img=22" },
  { name: "DanielUS",      avatarId: "avatar_templar",   titleId: "title_warrior",      level: 33, avatarColor: "#1565C0", avatarIcon: "shield-checkmark",photoUrl:"https://i.pravatar.cc/80?img=23"},
  { name: "EmmaUS",        avatarId: "avatar_harbinger", titleId: "title_predator",     level: 48, avatarColor: "#880E4F", avatarIcon: "warning",        photoUrl: "https://i.pravatar.cc/80?img=24" },
  { name: "NoahUS",        avatarId: "avatar_wraith",    titleId: "title_shadow2",      level: 62, avatarColor: "#4A148C", avatarIcon: "cloud",          photoUrl: "https://i.pravatar.cc/80?img=25" },
  { name: "OliviaCN",      avatarId: "avatar_sentinel",  titleId: "title_guardian_t",   level: 45, avatarColor: "#C62828", avatarIcon: "eye",            photoUrl: "https://i.pravatar.cc/80?img=26" },
  { name: "WilliamFR",     avatarId: "avatar_vanguard",  titleId: "title_challenger",   level: 39, avatarColor: "#1A237E", avatarIcon: "flag",           photoUrl: "https://i.pravatar.cc/80?img=27" },
  { name: "SophieFR",      avatarId: "avatar_sharpshooter",titleId:"title_predator",   level: 54, avatarColor: "#37474F", avatarIcon: "locate",         photoUrl: "https://i.pravatar.cc/80?img=28" },
  { name: "LiamIE",        avatarId: "avatar_overlord_av",titleId:"title_overlord",    level: 77, avatarColor: "#1B5E20", avatarIcon: "people",         photoUrl: "https://i.pravatar.cc/80?img=29" },
  { name: "AvaDK",         avatarId: "avatar_demigod",   titleId: "title_absolute",     level: 88, avatarColor: "#D4AF37", avatarIcon: "flash",          photoUrl: "https://i.pravatar.cc/80?img=30" },
  { name: "EthanCA",       avatarId: "avatar_entity",    titleId: "title_eternal",      level: 94, avatarColor: "#000000", avatarIcon: "help-circle" },
  { name: "MiaAU",         avatarId: "avatar_titan_god", titleId: "title_god",          level: 98, avatarColor: "#B0BEC5", avatarIcon: "barbell",        photoUrl: "https://i.pravatar.cc/80?img=32" },
  { name: "LucasDE",       avatarId: "avatar_emperor",   titleId: "title_eternal",      level: 82, avatarColor: "#D4AF37", avatarIcon: "ribbon",         photoUrl: "https://i.pravatar.cc/80?img=33" },
  { name: "IsabellaBR5",   avatarId: "avatar_celestial", titleId: "title_transcendent", level: 69, avatarColor: "#4FC3F7", avatarIcon: "planet",         photoUrl: "https://i.pravatar.cc/80?img=34" },
  { name: "MasonNZ",       avatarId: "avatar_chaos",     titleId: "title_maverick",     level: 56, avatarColor: "#A855F7", avatarIcon: "infinite",       photoUrl: "https://i.pravatar.cc/80?img=35" },
  { name: "EllaGB",        avatarId: "avatar_knight",    titleId: "title_competitor",   level: 14, avatarColor: "#37474F", avatarIcon: "shield",         photoUrl: "https://i.pravatar.cc/80?img=36" },
  { name: "JackGB",        avatarId: "avatar_wizard",    titleId: "title_expert",       level: 68, avatarColor: "#4527A0", avatarIcon: "sparkles",       photoUrl: "https://i.pravatar.cc/80?img=37" },
  { name: "AmelieGB",      avatarId: "avatar_samurai",   titleId: "title_noble",        level: 31, avatarColor: "#C62828", avatarIcon: "cut",            photoUrl: "https://i.pravatar.cc/80?img=38" },
  { name: "OliverSE",      avatarId: "avatar_pirate",    titleId: "title_outlaw",       level: 47, avatarColor: "#263238", avatarIcon: "skull",          photoUrl: "https://i.pravatar.cc/80?img=39" },
  { name: "SigridNO",      avatarId: "avatar_dragon",    titleId: "title_legend",       level: 73, avatarColor: "#1B5E20", avatarIcon: "flame",          photoUrl: "https://i.pravatar.cc/80?img=40" },
  { name: "KjeldDK",       avatarId: "avatar_cyber",     titleId: "title_expert",       level: 86, avatarColor: "#00BCD4", avatarIcon: "hardware-chip",  photoUrl: "https://i.pravatar.cc/80?img=41" },
  // ─── Profiles 301-400 ───────────────────────────────────────────────────────
  { name: "AkiraJP",       avatarId: "avatar_ninja",     titleId: "title_phantom",      level: 62, avatarColor: "#1A1A2E", avatarIcon: "eye-off" },
  { name: "YukiJP",        avatarId: "avatar_samurai",   titleId: "title_ace",          level: 45, avatarColor: "#D32F2F", avatarIcon: "cut",            photoUrl: "https://i.pravatar.cc/80?img=43" },
  { name: "HiroshiJP",     avatarId: "avatar_guardian",  titleId: "title_warrior",      level: 58, avatarColor: "#1565C0", avatarIcon: "shield-checkmark",photoUrl:"https://i.pravatar.cc/80?img=44"},
  { name: "KimJS",         avatarId: "avatar_mystic",    titleId: "title_transcendent", level: 79, avatarColor: "#9C27B0", avatarIcon: "help-circle",    photoUrl: "https://i.pravatar.cc/80?img=45" },
  { name: "MinJiKR",       avatarId: "avatar_wizard",    titleId: "title_mastermind",   level: 53, avatarColor: "#6A1B9A", avatarIcon: "sparkles",       photoUrl: "https://i.pravatar.cc/80?img=46" },
  { name: "ChengCN",       avatarId: "avatar_titan",     titleId: "title_god",          level: 88, avatarColor: "#78909C", avatarIcon: "barbell",        photoUrl: "https://i.pravatar.cc/80?img=47" },
  { name: "WeiCN",         avatarId: "avatar_dragon",    titleId: "title_invincible",   level: 71, avatarColor: "#D32F2F", avatarIcon: "flame",          photoUrl: "https://i.pravatar.cc/80?img=48" },
  { name: "FangCN",        avatarId: "avatar_sorcerer",  titleId: "title_absolute",     level: 92, avatarColor: "#4A148C", avatarIcon: "planet",         photoUrl: "https://i.pravatar.cc/80?img=49" },
  { name: "PriyaIN",       avatarId: "avatar_scholar",   titleId: "title_strategist",   level: 36, avatarColor: "#F06292", avatarIcon: "book",           photoUrl: "https://i.pravatar.cc/80?img=50" },
  { name: "RajIN",         avatarId: "avatar_gladiator", titleId: "title_warrior",      level: 49, avatarColor: "#B71C1C", avatarIcon: "trophy",         photoUrl: "https://i.pravatar.cc/80?img=51" },
  { name: "AmirIR",        avatarId: "avatar_assassin",  titleId: "title_predator",     level: 65, avatarColor: "#212121", avatarIcon: "warning",        photoUrl: "https://i.pravatar.cc/80?img=52" },
  { name: "NiloufarUZ",    avatarId: "avatar_valkyrie",  titleId: "title_competitor",   level: 28, avatarColor: "#F0E68C", avatarIcon: "person",         photoUrl: "https://i.pravatar.cc/80?img=53" },
  { name: "DmitriRU",      avatarId: "avatar_berserker", titleId: "title_invincible",   level: 77, avatarColor: "#C62828", avatarIcon: "flash",          photoUrl: "https://i.pravatar.cc/80?img=54" },
  { name: "NatashaRU",     avatarId: "avatar_spy",       titleId: "title_shadow2",      level: 61, avatarColor: "#263238", avatarIcon: "eye-off",        photoUrl: "https://i.pravatar.cc/80?img=55" },
  { name: "IvanUA",        avatarId: "avatar_knight",    titleId: "title_warrior",      level: 44, avatarColor: "#1565C0", avatarIcon: "shield",         photoUrl: "https://i.pravatar.cc/80?img=56" },
  { name: "OlgaPL",        avatarId: "avatar_druid",     titleId: "title_dreamer",      level: 23, avatarColor: "#2E7D32", avatarIcon: "leaf",           photoUrl: "https://i.pravatar.cc/80?img=57" },
  { name: "ZbigniewPL",    avatarId: "avatar_gladiator", titleId: "title_veteran",      level: 38, avatarColor: "#880E4F", avatarIcon: "trophy",         photoUrl: "https://i.pravatar.cc/80?img=58" },
  { name: "MohammedAE",    avatarId: "avatar_warlord",   titleId: "title_overlord",     level: 82, avatarColor: "#B71C1C", avatarIcon: "people",         photoUrl: "https://i.pravatar.cc/80?img=59" },
  { name: "FatimaTR",      avatarId: "avatar_oracle",    titleId: "title_believer",     level: 35, avatarColor: "#7C4DFF", avatarIcon: "eye",            photoUrl: "https://i.pravatar.cc/80?img=60" },
  { name: "MehmetTR",      avatarId: "avatar_corsair",   titleId: "title_renegade",     level: 54, avatarColor: "#1A237E", avatarIcon: "boat",           photoUrl: "https://i.pravatar.cc/80?img=61" },
  { name: "LinaEG",        avatarId: "avatar_astrologer",titleId: "title_observer",     level: 19, avatarColor: "#F57F17", avatarIcon: "star",           photoUrl: "https://i.pravatar.cc/80?img=62" },
  { name: "MoussaNG",      avatarId: "avatar_beastmaster",titleId:"title_warrior",      level: 41, avatarColor: "#5D4037", avatarIcon: "paw",            photoUrl: "https://i.pravatar.cc/80?img=63" },
  { name: "KwameGH",       avatarId: "avatar_phoenix",   titleId: "title_comeback",     level: 56, avatarColor: "#FF6F00", avatarIcon: "sunny",          photoUrl: "https://i.pravatar.cc/80?img=64" },
  { name: "AmadouSN",      avatarId: "avatar_titan",     titleId: "title_competitor",   level: 33, avatarColor: "#6D4C41", avatarIcon: "barbell",        photoUrl: "https://i.pravatar.cc/80?img=65" },
  { name: "AishaKE",       avatarId: "avatar_mystic",    titleId: "title_dreamer",      level: 22, avatarColor: "#9C27B0", avatarIcon: "help-circle",    photoUrl: "https://i.pravatar.cc/80?img=66" },
  { name: "NjokuNG",       avatarId: "avatar_gladiator_rare",titleId:"title_shark",     level: 47, avatarColor: "#37474F", avatarIcon: "trophy",         photoUrl: "https://i.pravatar.cc/80?img=67" },
  { name: "TamarZA",       avatarId: "avatar_valkyrie",  titleId: "title_invincible",   level: 64, avatarColor: "#B8860B", avatarIcon: "person",         photoUrl: "https://i.pravatar.cc/80?img=68" },
  { name: "KalebET",       avatarId: "avatar_warrior2",  titleId: "title_warrior",      level: 29, avatarColor: "#4E342E", avatarIcon: "shield",         photoUrl: "https://i.pravatar.cc/80?img=69" },
  { name: "DinahEG",       avatarId: "avatar_scholar",   titleId: "title_strategist",   level: 15, avatarColor: "#F06292", avatarIcon: "book",           photoUrl: "https://i.pravatar.cc/80?img=70" },
  { name: "AntonioIT2",    avatarId: "avatar_wizard",    titleId: "title_grandmaster",  level: 75, avatarColor: "#6A1B9A", avatarIcon: "sparkles",       photoUrl: "https://i.pravatar.cc/80?img=71" },
  { name: "GiovannaPT",    avatarId: "avatar_artist",    titleId: "title_dreamer",      level: 30, avatarColor: "#880E4F", avatarIcon: "color-palette",  photoUrl: "https://i.pravatar.cc/80?img=72" },
  { name: "FilipeFR2",     avatarId: "avatar_samurai",   titleId: "title_challenger",   level: 43, avatarColor: "#1565C0", avatarIcon: "cut",            photoUrl: "https://i.pravatar.cc/80?img=73" },
  { name: "CarlottaFR",    avatarId: "avatar_necromancer",titleId:"title_dark_lord",    level: 59, avatarColor: "#4A148C", avatarIcon: "skull",          photoUrl: "https://i.pravatar.cc/80?img=74" },
  { name: "PierreCA2",     avatarId: "avatar_dragon",    titleId: "title_invincible",   level: 78, avatarColor: "#B71C1C", avatarIcon: "flame",          photoUrl: "https://i.pravatar.cc/80?img=75" },
  { name: "ClaireFR3",     avatarId: "avatar_oracle",    titleId: "title_mastermind",   level: 52, avatarColor: "#7C4DFF", avatarIcon: "eye",            photoUrl: "https://i.pravatar.cc/80?img=76" },
  { name: "ThorstenDE",    avatarId: "avatar_berserker", titleId: "title_warrior",      level: 66, avatarColor: "#37474F", avatarIcon: "flash",          photoUrl: "https://i.pravatar.cc/80?img=77" },
  { name: "IngridSE2",     avatarId: "avatar_valkyrie",  titleId: "title_noble",        level: 37, avatarColor: "#D4AF37", avatarIcon: "person",         photoUrl: "https://i.pravatar.cc/80?img=78" },
  { name: "GunnardNO",     avatarId: "avatar_warlord",   titleId: "title_overlord",     level: 85, avatarColor: "#880E4F", avatarIcon: "people",         photoUrl: "https://i.pravatar.cc/80?img=79" },
  { name: "HelgaFI",       avatarId: "avatar_druid",     titleId: "title_guardian_t",   level: 21, avatarColor: "#2E7D32", avatarIcon: "leaf",           photoUrl: "https://i.pravatar.cc/80?img=80" },
  { name: "MikkelDK2",     avatarId: "avatar_assassin",  titleId: "title_phantom",      level: 48, avatarColor: "#1A1A2E", avatarIcon: "warning",        photoUrl: "https://i.pravatar.cc/80?img=1"  },
  { name: "ToveSE",        avatarId: "avatar_sorcerer",  titleId: "title_transcendent", level: 71, avatarColor: "#6A1B9A", avatarIcon: "planet",         photoUrl: "https://i.pravatar.cc/80?img=2"  },
  { name: "EliasNO2",      avatarId: "avatar_conqueror", titleId: "title_invincible",   level: 56, avatarColor: "#D32F2F", avatarIcon: "flag",           photoUrl: "https://i.pravatar.cc/80?img=3"  },
  { name: "StefanosGR",    avatarId: "avatar_gladiator", titleId: "title_warrior",      level: 40, avatarColor: "#880E4F", avatarIcon: "trophy",         photoUrl: "https://i.pravatar.cc/80?img=4"  },
  { name: "EleftheriaCY",  avatarId: "avatar_mystic",    titleId: "title_dreamer",      level: 25, avatarColor: "#7B1FA2", avatarIcon: "help-circle",    photoUrl: "https://i.pravatar.cc/80?img=5"  },
  { name: "NikolasSR",     avatarId: "avatar_knight",    titleId: "title_warrior",      level: 34, avatarColor: "#37474F", avatarIcon: "shield",         photoUrl: "https://i.pravatar.cc/80?img=6"  },
  { name: "MilicaRS",      avatarId: "avatar_archer2",   titleId: "title_predator",     level: 47, avatarColor: "#2E7D32", avatarIcon: "locate",         photoUrl: "https://i.pravatar.cc/80?img=7"  },
  { name: "DraganHR",      avatarId: "avatar_berserker", titleId: "title_invincible",   level: 65, avatarColor: "#B71C1C", avatarIcon: "flash",          photoUrl: "https://i.pravatar.cc/80?img=8"  },
  { name: "TanjaBG",       avatarId: "avatar_oracle",    titleId: "title_strategist",   level: 28, avatarColor: "#7C4DFF", avatarIcon: "eye",            photoUrl: "https://i.pravatar.cc/80?img=9"  },
  { name: "PetarX",       avatarId: "avatar_gladiator", titleId: "title_warrior",      level: 52, avatarColor: "#B71C1C", avatarIcon: "trophy",         photoUrl: "https://i.pravatar.cc/80?img=10" },
  { name: "AndreiUA2",     avatarId: "avatar_spy",       titleId: "title_renegade",     level: 39, avatarColor: "#263238", avatarIcon: "eye-off",        photoUrl: "https://i.pravatar.cc/80?img=11" },
  // ─── Profiles 401-500 ───────────────────────────────────────────────────────
  { name: "VictorHU",      avatarId: "avatar_titan",     titleId: "title_warrior",      level: 57, avatarColor: "#6D4C41", avatarIcon: "barbell",        photoUrl: "https://i.pravatar.cc/80?img=12" },
  { name: "AnnaMX7",       avatarId: "avatar_wizard",    titleId: "title_strategist",   level: 11, avatarColor: "#9C27B0", avatarIcon: "sparkles",       photoUrl: "https://i.pravatar.cc/80?img=13" },
  { name: "OscarAR5",      avatarId: "avatar_dragon",    titleId: "title_ace",          level: 73, avatarColor: "#D32F2F", avatarIcon: "flame",          photoUrl: "https://i.pravatar.cc/80?img=14" },
  { name: "PaulaBR6",      avatarId: "avatar_valkyrie",  titleId: "title_competitor",   level: 26, avatarColor: "#F0E68C", avatarIcon: "person",         photoUrl: "https://i.pravatar.cc/80?img=15" },
  { name: "JorgeAR6",      avatarId: "avatar_cyber",     titleId: "title_immortal",     level: 84, avatarColor: "#00BCD4", avatarIcon: "hardware-chip",  photoUrl: "https://i.pravatar.cc/80?img=16" },
  { name: "MargaritaBR7",  avatarId: "avatar_phoenix",   titleId: "title_comeback",     level: 35, avatarColor: "#FF6F00", avatarIcon: "sunny",          photoUrl: "https://i.pravatar.cc/80?img=17" },
  { name: "AlejoCO7",      avatarId: "avatar_reaper",    titleId: "title_dark_lord",    level: 91, avatarColor: "#4A148C", avatarIcon: "skull" },
  { name: "RosaVE5",       avatarId: "avatar_oracle",    titleId: "title_mastermind",   level: 44, avatarColor: "#7C4DFF", avatarIcon: "eye",            photoUrl: "https://i.pravatar.cc/80?img=19" },
  { name: "LuisMX8",       avatarId: "avatar_knight",    titleId: "title_veteran",      level: 19, avatarColor: "#1565C0", avatarIcon: "shield",         photoUrl: "https://i.pravatar.cc/80?img=20" },
  { name: "IsabelAR7",     avatarId: "avatar_assassin",  titleId: "title_shadow2",      level: 60, avatarColor: "#212121", avatarIcon: "warning",        photoUrl: "https://i.pravatar.cc/80?img=21" },
  { name: "FabioCO8",      avatarId: "avatar_bard",      titleId: "title_casual",       level: 7,  avatarColor: "#7B1FA2", avatarIcon: "musical-notes",  photoUrl: "https://i.pravatar.cc/80?img=22" },
  { name: "ClarissaBR8",   avatarId: "avatar_mystic",    titleId: "title_observer",     level: 31, avatarColor: "#9C27B0", avatarIcon: "help-circle",    photoUrl: "https://i.pravatar.cc/80?img=23" },
  { name: "PedroMX9",      avatarId: "avatar_gladiator", titleId: "title_shark",        level: 55, avatarColor: "#880E4F", avatarIcon: "trophy",         photoUrl: "https://i.pravatar.cc/80?img=24" },
  { name: "YamilaAR8",     avatarId: "avatar_sorcerer",  titleId: "title_transcendent", level: 79, avatarColor: "#6A1B9A", avatarIcon: "planet",         photoUrl: "https://i.pravatar.cc/80?img=25" },
  { name: "GuillermoCO9",  avatarId: "avatar_warlord",   titleId: "title_overlord",     level: 93, avatarColor: "#B71C1C", avatarIcon: "people",         photoUrl: "https://i.pravatar.cc/80?img=26" },
  { name: "MarisolBR9",    avatarId: "avatar_berserker", titleId: "title_invincible",   level: 66, avatarColor: "#D32F2F", avatarIcon: "flash",          photoUrl: "https://i.pravatar.cc/80?img=27" },
  { name: "DavidoNG2",     avatarId: "avatar_titan",     titleId: "title_legend",       level: 80, avatarColor: "#FF6F00", avatarIcon: "barbell",        photoUrl: "https://i.pravatar.cc/80?img=28" },
  { name: "EmekaNGR",      avatarId: "avatar_warrior2",  titleId: "title_warrior",      level: 38, avatarColor: "#4E342E", avatarIcon: "shield",         photoUrl: "https://i.pravatar.cc/80?img=29" },
  { name: "ChibuzorNG3",   avatarId: "avatar_gladiator", titleId: "title_predator",     level: 52, avatarColor: "#B71C1C", avatarIcon: "trophy",         photoUrl: "https://i.pravatar.cc/80?img=30" },
  { name: "OkonkwoNG4",    avatarId: "avatar_beastmaster",titleId:"title_warrior",      level: 44, avatarColor: "#5D4037", avatarIcon: "paw",            photoUrl: "https://i.pravatar.cc/80?img=31" },
  { name: "TundeNG5",      avatarId: "avatar_conqueror", titleId: "title_challenger",   level: 28, avatarColor: "#37474F", avatarIcon: "flag",           photoUrl: "https://i.pravatar.cc/80?img=32" },
  { name: "FolakeNG6",     avatarId: "avatar_oracle",    titleId: "title_believer",     level: 17, avatarColor: "#9C27B0", avatarIcon: "eye",            photoUrl: "https://i.pravatar.cc/80?img=33" },
  { name: "AbiolaNG7",     avatarId: "avatar_mystic",    titleId: "title_dreamer",      level: 35, avatarColor: "#7B1FA2", avatarIcon: "help-circle",    photoUrl: "https://i.pravatar.cc/80?img=34" },
  { name: "SeunNG8",       avatarId: "avatar_assassin",  titleId: "title_predator",     level: 62, avatarColor: "#212121", avatarIcon: "warning",        photoUrl: "https://i.pravatar.cc/80?img=35" },
  { name: "BimpeNG9",      avatarId: "avatar_sorcerer",  titleId: "title_absolute",     level: 77, avatarColor: "#6A1B9A", avatarIcon: "planet",         photoUrl: "https://i.pravatar.cc/80?img=36" },
  { name: "KemiNG10",      avatarId: "avatar_valkyrie",  titleId: "title_noble",        level: 24, avatarColor: "#D4AF37", avatarIcon: "person",         photoUrl: "https://i.pravatar.cc/80?img=37" },
  { name: "ChukwuNG11",    avatarId: "avatar_titan",     titleId: "title_god",          level: 89, avatarColor: "#6D4C41", avatarIcon: "barbell",        photoUrl: "https://i.pravatar.cc/80?img=38" },
  { name: "YetundeNG12",   avatarId: "avatar_wizard",    titleId: "title_grandmaster",  level: 47, avatarColor: "#9C27B0", avatarIcon: "sparkles",       photoUrl: "https://i.pravatar.cc/80?img=39" },
  { name: "GbengaNG13",    avatarId: "avatar_dragon",    titleId: "title_shark",        level: 68, avatarColor: "#D32F2F", avatarIcon: "flame",          photoUrl: "https://i.pravatar.cc/80?img=40" },
  { name: "RonkeNG14",     avatarId: "avatar_scholar",   titleId: "title_observer",     level: 13, avatarColor: "#F06292", avatarIcon: "book",           photoUrl: "https://i.pravatar.cc/80?img=41" },
  { name: "KolaNG15",      avatarId: "avatar_knight",    titleId: "title_veteran",      level: 55, avatarColor: "#546E7A", avatarIcon: "shield",         photoUrl: "https://i.pravatar.cc/80?img=42" },
  { name: "AdeNG16",       avatarId: "avatar_gladiator_rare",titleId:"title_ace",       level: 40, avatarColor: "#880E4F", avatarIcon: "trophy",         photoUrl: "https://i.pravatar.cc/80?img=43" },
  { name: "IbrahimSN2",    avatarId: "avatar_ranger",    titleId: "title_hunter",       level: 32, avatarColor: "#2E7D32", avatarIcon: "arrow-forward",  photoUrl: "https://i.pravatar.cc/80?img=44" },
  { name: "MaremSN3",      avatarId: "avatar_bard",      titleId: "title_dreamer",      level: 11, avatarColor: "#FF8F00", avatarIcon: "musical-notes",  photoUrl: "https://i.pravatar.cc/80?img=45" },
  { name: "OusmaneML",     avatarId: "avatar_warrior2",  titleId: "title_warrior",      level: 48, avatarColor: "#4E342E", avatarIcon: "shield",         photoUrl: "https://i.pravatar.cc/80?img=46" },
  { name: "FatouGW",       avatarId: "avatar_valkyrie",  titleId: "title_competitor",   level: 23, avatarColor: "#F0E68C", avatarIcon: "person",         photoUrl: "https://i.pravatar.cc/80?img=47" },
  { name: "MouhamadouTD",  avatarId: "avatar_gladiator", titleId: "title_invincible",   level: 64, avatarColor: "#B71C1C", avatarIcon: "trophy",         photoUrl: "https://i.pravatar.cc/80?img=48" },
  { name: "SekouGN",       avatarId: "avatar_titan",     titleId: "title_legend",       level: 76, avatarColor: "#37474F", avatarIcon: "barbell",        photoUrl: "https://i.pravatar.cc/80?img=49" },
  { name: "LantaCM",       avatarId: "avatar_mystic",    titleId: "title_observer",     level: 19, avatarColor: "#9C27B0", avatarIcon: "help-circle",    photoUrl: "https://i.pravatar.cc/80?img=50" },
  { name: "DialloBF",      avatarId: "avatar_shaman",    titleId: "title_believer",     level: 36, avatarColor: "#5D4037", avatarIcon: "bonfire",        photoUrl: "https://i.pravatar.cc/80?img=51" },
  { name: "BahCIV",        avatarId: "avatar_beastmaster",titleId:"title_warrior",      level: 54, avatarColor: "#4E342E", avatarIcon: "paw",            photoUrl: "https://i.pravatar.cc/80?img=52" },
  { name: "KouadioCI2",    avatarId: "avatar_dragon",    titleId: "title_ace",          level: 72, avatarColor: "#1B5E20", avatarIcon: "flame",          photoUrl: "https://i.pravatar.cc/80?img=53" },
  { name: "YaoCIV",        avatarId: "avatar_oracle",    titleId: "title_mastermind",   level: 45, avatarColor: "#7C4DFF", avatarIcon: "eye",            photoUrl: "https://i.pravatar.cc/80?img=54" },
  { name: "AkossiGH2",     avatarId: "avatar_knight",    titleId: "title_veteran",      level: 29, avatarColor: "#1565C0", avatarIcon: "shield",         photoUrl: "https://i.pravatar.cc/80?img=55" },
  { name: "NanaGH3",       avatarId: "avatar_wizard",    titleId: "title_strategist",   level: 17, avatarColor: "#7B1FA2", avatarIcon: "sparkles",       photoUrl: "https://i.pravatar.cc/80?img=56" },
  { name: "KwesiGH4",      avatarId: "avatar_samurai",   titleId: "title_ace",          level: 61, avatarColor: "#0D47A1", avatarIcon: "cut",            photoUrl: "https://i.pravatar.cc/80?img=57" },
  { name: "AbenaGH5",      avatarId: "avatar_scholar",   titleId: "title_regular",      level: 8,  avatarColor: "#F06292", avatarIcon: "book",           photoUrl: "https://i.pravatar.cc/80?img=58" },
  { name: "EfiaMX10",      avatarId: "avatar_pirate",    titleId: "title_outlaw",       level: 43, avatarColor: "#263238", avatarIcon: "skull",          photoUrl: "https://i.pravatar.cc/80?img=59" },
  { name: "CofieMX11",     avatarId: "avatar_gladiator_rare",titleId:"title_shark",     level: 57, avatarColor: "#37474F", avatarIcon: "trophy",         photoUrl: "https://i.pravatar.cc/80?img=60" },
  { name: "QuasiMX12",     avatarId: "avatar_necromancer",titleId:"title_dark_lord",    level: 84, avatarColor: "#4A148C", avatarIcon: "skull",          photoUrl: "https://i.pravatar.cc/80?img=61" },
  { name: "AsamoahMX13",   avatarId: "avatar_titan",     titleId: "title_god",          level: 96, avatarColor: "#78909C", avatarIcon: "barbell",        photoUrl: "https://i.pravatar.cc/80?img=62" },
  { name: "AmponsahMX14",  avatarId: "avatar_sorcerer",  titleId: "title_absolute",     level: 78, avatarColor: "#4A148C", avatarIcon: "planet",         photoUrl: "https://i.pravatar.cc/80?img=63" },
  { name: "OwusuMX15",     avatarId: "avatar_conqueror", titleId: "title_invincible",   level: 65, avatarColor: "#B71C1C", avatarIcon: "flag",           photoUrl: "https://i.pravatar.cc/80?img=64" },
  { name: "MensahMX16",    avatarId: "avatar_guardian",  titleId: "title_warrior",      level: 33, avatarColor: "#37474F", avatarIcon: "shield-checkmark",photoUrl:"https://i.pravatar.cc/80?img=65"},
  { name: "OduroMX17",     avatarId: "avatar_warlord",   titleId: "title_overlord",     level: 90, avatarColor: "#880E4F", avatarIcon: "people",         photoUrl: "https://i.pravatar.cc/80?img=66" },
  { name: "BoakyeMX18",    avatarId: "avatar_berserker", titleId: "title_invincible",   level: 73, avatarColor: "#C62828", avatarIcon: "flash",          photoUrl: "https://i.pravatar.cc/80?img=67" },
  { name: "OforiMX19",     avatarId: "avatar_assassin",  titleId: "title_predator",     level: 50, avatarColor: "#212121", avatarIcon: "warning",        photoUrl: "https://i.pravatar.cc/80?img=68" },
  { name: "DomfehMX20",    avatarId: "avatar_archmage",  titleId: "title_transcendent", level: 87, avatarColor: "#4527A0", avatarIcon: "sparkles",       photoUrl: "https://i.pravatar.cc/80?img=69" },
  { name: "AsanteMX21",    avatarId: "avatar_emperor",   titleId: "title_eternal",      level: 99, avatarColor: "#D4AF37", avatarIcon: "ribbon" },
];

export function getRandomCpuProfile(seed?: number, playerLevel?: number, isExpert?: boolean): CpuProfile {
  if (isExpert) {
    const experts = CPU_PROFILES.filter(p => p.level >= 80);
    const pool = experts.length > 0 ? experts : CPU_PROFILES;
    const idx = seed !== undefined ? Math.abs(seed) % pool.length : Math.floor(Math.random() * pool.length);
    return pool[idx];
  }

  if (playerLevel !== undefined) {
    const minLevel = Math.max(1, playerLevel - 5);
    const maxLevel = playerLevel + 5;
    const nearby = CPU_PROFILES.filter(p => p.level >= minLevel && p.level <= maxLevel);
    
    if (nearby.length > 0) {
      const idx = seed !== undefined ? Math.abs(seed) % nearby.length : Math.floor(Math.random() * nearby.length);
      return nearby[idx];
    }
    
    // Fallback: pick from 10 closest
    const sorted = [...CPU_PROFILES].sort((a, b) => Math.abs(a.level - playerLevel) - Math.abs(b.level - playerLevel));
    const pool = sorted.slice(0, 10);
    const idx = seed !== undefined ? Math.abs(seed) % pool.length : Math.floor(Math.random() * pool.length);
    return pool[idx];
  }

  const idx = seed !== undefined
    ? Math.abs(seed) % CPU_PROFILES.length
    : Math.floor(Math.random() * CPU_PROFILES.length);
  return CPU_PROFILES[idx];
}

export function pickCpuProfiles(n: number, playerLevelOrSeed?: number, playerLevel?: number, isExpert?: boolean): CpuProfile[] {
  // Use the massive rival generator for true 100k-profile variety
  const level = playerLevel ?? playerLevelOrSeed ?? 1;
  const rivals = pickRivalProfiles(n, level);
  if (rivals.length >= n) return rivals;

  // Fallback to classic pool if generator can't fill
  const pool = isExpert
    ? CPU_PROFILES.filter(p => p.level >= 80)
    : level > 1
      ? CPU_PROFILES.filter(p => p.level >= Math.max(1, level - 5) && p.level <= level + 5)
      : CPU_PROFILES;

  const actualPool = pool.length >= n ? pool : CPU_PROFILES;
  const total = actualPool.length;
  const picks: CpuProfile[] = [...rivals];
  const used = new Set<number>();
  let s = Math.floor(Math.random() * 1000000);

  while (picks.length < Math.min(n, total + rivals.length)) {
    const idx = Math.abs(s) % total;
    if (!used.has(idx)) {
      picks.push(actualPool[idx]);
      used.add(idx);
    }
    s = (s * 1103515245 + 12345) & 0x7fffffff;
    if (used.size === total) break;
  }
  return picks.slice(0, n);
}
